### ISSUE TITLE
The WAR button always appears disabled

### ISSUE THREAD

**Issue by omenukas** [edterbak/NodeRed_Heishamon_control#101]
Hello,

The heat pump works according to the curve. However, the dashboard shows that WAR is disabled. When I try to turn it on, after a few seconds the WAR button goes back to the "off" state. I tried with the pump on and off.
In the log it looks like this:
11/02 12:41:11 - Function - WAR: 0
11/02 12:41:08 - Function - WAR: 1
![image](https://user-images.githubusercontent.com/122688908/218256006-761452e3-948f-472e-9dcd-97d198e80de4.png)

**Comment by LaMiyu** [comment]
Hello,

I had the same problem when I had the WP itself still in Compensation Curve mode.
Switching to direct mode solved the problem for me.

**Comment by omenukas** [comment]
> Hello,
> 
> I had the same problem when I had the WP itself still in Compensation Curve mode. Switching to direct mode solved the problem for me.

Yes...that's how I solved this problem too :)

**Comment by edterbak** [comment]
Yes, this is not a bug.

If you use the compensation curve inside the panasonic, the panasonic is doing this same function. 
Difference is, that the panasonic hardcoded uses the temperature reading outside of the panasonic itself. (sometimes useless in sunlight)

So the two functions are the same and cannot be active at the same time. :) 
If I read you are using compensation curve, I force the node red WAR function to disable. :)
