### ISSUE TITLE
[ENHANCEMENT]: Quiet Mode Level in SoftStart graph

### ISSUE THREAD

**Issue by blb4github** [edterbak/NodeRed_Heishamon_control#104]
**Is your feature request related to a problem or use case? Please describe.**
It would be nice to have Quiet Mode level (0,1, 2, or 3) in the Softstart graph

**Describe the solution you'd like**
As above, 'just' add the Quiet Mode level in the graph. With this enhancement it's easier to see the impact of QM level on the compressor Hz.

**Comment by edterbak** [comment]
Ok

**Comment by edterbak** [comment]
![image](https://user-images.githubusercontent.com/3155621/227325532-f664b41a-4cbf-4a06-aa51-896dd0465bc8.png)
Added

**Comment by blb4github** [comment]
You're the best!!
