### ISSUE TITLE
[ENHANCEMENT]: Pump speed control during DHW production

### ISSUE THREAD

**Issue by blb4github** [edterbak/NodeRed_Heishamon_control#105]
**Is your feature request related to a problem or **use case**? Please describe.**
It turns out the compressor frequency / Power during DHW can be controlled by setting the pump speed **before** the DHW run starts. In my situation I work by default with a low (reduced) pump speed (19%) and I noticed DHW run is done with max 35 Hz where most people 'complain' the DHW run is with max power/Hz. By setting the pump speed to 50% in advance the DHW run did go on full speed. This knowledge can be used to control power during DHW run, the DHW run must be planned in advance in that case.

**Describe the solution you'd like**
- On the settings page an additional slider for "DHW pump speed";
- With every planned DHW run:
         1. DHW/Sterilisation via home page or settings page;
         2. DHW/Sterilisation via scheduler;
         3. switching to an operation mode including DHW when DHW temperature < DHW target temperature;
   the pump speed will be set to "DHW pump speed" and once the DHW run is finished the pump speed will be set back to normal.

**Describe alternatives you've considered**
Maybe the pump speed can be (still) set when 3-way valve is set to DHW, this would be the easiest trigger (and change back to normal if 3-way valve returns to default. I will test this.

**Comment by edterbak** [comment]
Nice.

If there is a desire to have this, I first only want to implement this through the scheduler, option 2. All other sources are not easy to realize. The opposite actually. 

The scheduler can send multiple outputs, like set operating mode, set temperature, set pump speed. Even with built in delays between eachother. 
This is not possible when using a toggle on a dashboard. IF there is logic behind a toggle, chances are users are able to break other logic and dependancies with ease.

**Comment by edterbak** [comment]
Built in v22.21. Needs reviewing

**Comment by edterbak** [comment]
I considder it to be working ok. If there are errors, I would have expected to hear from them already :) 
If there are bugs, we need to create a new bug report.

**Comment by blb4github** [comment]
All working fine indeed as far as I can see, thanks!!
