### ISSUE TITLE
Request: Set silent mode above set temperature

### ISSUE THREAD

**Issue by timovd** [edterbak/NodeRed_Heishamon_control#11]
Feature request. Currently, in The Netherlands, it's quite warm for a winter. When the outdoor temperature reaches a certain temperature, I'd like to activate silent mode 3 to slow down the compressor frequency and have longer runs.

**Comment by edterbak** [comment]
I have read your request. It will need some thinking for 2 reasons. 
A: Is this a good approach and B, if so, how to build it.

**Comment by timovd** [comment]
currently Softstart is not working for me due to #14 If I know that the issue is here, this might not be needed.
