### ISSUE TITLE
[BUG]: night reduction in 22.28

### ISSUE THREAD

**Issue by LaMiyu** [edterbak/NodeRed_Heishamon_control#111]
Hello,

I just installed the 22.28 - the night reduction work not correct.

In schedular is set to -4
In the main Dashboard it shows +1

![image](https://github.com/edterbak/NodeRed_Heishamon_control/assets/73053267/0c7db8ee-d761-48e4-b68e-e58aa4fad01b)

![image](https://github.com/edterbak/NodeRed_Heishamon_control/assets/73053267/fa48d9b1-b1ab-49fd-97e0-e57056576749)

**Comment by edterbak** [comment]
Yes. That does not look right.
I will investigate tonight

Thanks for the report

**Comment by edterbak** [comment]
Amateur error. fixed in next release (v22.30)

**Comment by edterbak** [comment]
@LaMiyu 
New version online, v22.30. this should be fixed now. If you confirm, we (you or I) can close the issue. :)

**Comment by LaMiyu** [comment]
tested in v22.31 - fixed :)
