### ISSUE TITLE
[ENHANCEMENT]: Heishamon Offline - Command Lost

### ISSUE THREAD

**Issue by LaMiyu** [edterbak/NodeRed_Heishamon_control#112]
Hello,

I installed a hood over the jeisha to cut down on the noise a bit.
This is degrading my wifi signal. 
(Wifi Quality in Heishamon is at 20%).

In the logs online/offline also changes all the time.
If a command is sent when the Jeisha is offline, it is lost. 

![image](https://github.com/edterbak/NodeRed_Heishamon_control/assets/73053267/81d7f717-7907-4973-a878-2432adfddd08)

I think it would be useful to check before sending if the heat pump is currently offline and if so send the command again in maybe 30sec? Or wait until the status is back online and then send the command ... this would of course also be limited, not that in the end 50 commands waiting for the heat pump to come online.

I think, however, a small buffer to intercept a short offline would be useful in many functions and make the solution more stable.
Unfortunately, there is no Ethernet connection to bypass the wifi problem.

**Comment by LaMiyu** [comment]
Of course I have to do something on my wifi - I think that is currently the extreme case.
Nevertheless, there can be a short outage at any time or Heishamon loses the connection.

I think it would be annoying if the heating of the hot water fails and you notice it only when you stand under the cold shower.

**Comment by edterbak** [comment]
I have done some inquiries around this. 
not a easy fix. 
Need to make the flow aware of the sent command, and the actual value. 
I will put this on the board for later. It is not a quick one.

in the mean time, you could investigate a solution like this:
![image](https://github.com/edterbak/NodeRed_Heishamon_control/assets/3155621/a6bbccc8-bf0c-49f1-b8bc-301619084c42)
It is available and described on the tindie site.
https://www.tindie.com/products/thehognl/heishamon-communication-pcb/

Hope this helps.

**Comment by edterbak** [comment]
Hi Lamiyu 
Is this solved?
