### ISSUE TITLE
Unexpected Restart of Flow an Venus OS

### ISSUE THREAD

**Issue by usauerbrey** [edterbak/NodeRed_Heishamon_control#117]
I am running NodeRed_Heishamon_control on a Raspi 3+ under Venus OS. 
The Flow restarts every 5-10 min, lately after 30 min, but the log does not help.
Is there any known problem with Venus OS or could it be too less memory (TOP does no say so) or do you have any other idea how do fix this.

Thanks Uwe

**Comment by edterbak** [comment]
I do not know Venus OS. I have no experience running this on a raspbery pi 3. I can not comment on the hardware requirements for this. 

How much RAM does the pi3 have?

**Comment by usauerbrey** [comment]
The Raspi has 1GB, TOP says: 
Mem: 609444K used, 334836K free, 1980K shrd, 37428K buff, 74920K cached
CPU:  43% usr   8% sys   0% nic  44% idle   0% io   2% irq   0% sirq
Load average: 3.23 3.23 2.63 4/311 15404

**Comment by edterbak** [comment]
It should be sufficient.  I gave my container 2GB, but it is only using <400MB
![image](https://github.com/edterbak/NodeRed_Heishamon_control/assets/3155621/5db1e3ef-8d08-48c8-8291-e61eaabffe08)

Do you see error messages in the debug screen? 
What messages do you see in the log?

**Comment by edterbak** [comment]
What version of node red is being used?

**Comment by usauerbrey** [comment]
Node Red: 3.0.2
the log says:
24/06 15:58:12 - Function - WAR: 0
24/06 15:58:02 - Function SoftStart: SoftStart function end
24/06 15:58:02 - Compressor: stopped
24/06 15:58:02 - Function Pump speed: Max pumpspeed set to undefined (NaN%) (Low)
24/06 15:58:01 - SYSTEM: MQTT block inactive, default block mode: BLOCK ALL
24/06 15:57:58 - SYSTEM: WAR settings OK
24/06 15:57:58 - SETUP - Sensors: Custom room temperature sensor not found. Using internal sensor (TOP33)
24/06 15:57:58 - SYSTEM: Heatpump is WAR mode (compensation curve)
24/06 15:57:58 - Function - SoftStart: 1
24/06 15:57:58 - Function Solar: 0
24/06 15:57:58 - Function NightReduction: 0
24/06 15:58:00 - SYSTEM - HEISHAMON Connection: Online
24/06 15:57:57 - SYSTEM - HEISHAMON Connection: Offline
24/06 15:57:50 - SYSTEM: Start---------------------------------------------------------------
------------------------------------------------------------------------------------------------
24/06 15:56:49 - Function - WAR: 0
24/06 15:56:36 - Function SoftStart: SoftStart function end
24/06 15:56:36 - Compressor: stopped
24/06 15:56:34 - Function Pump speed: Max pumpspeed set to undefined (NaN%) (Low)
24/06 15:56:33 - SYSTEM: MQTT block inactive, default block mode: BLOCK ALL
24/06 15:56:31 - SYSTEM: WAR settings OK
24/06 15:56:31 - SETUP - Sensors: Custom room temperature sensor not found. Using internal sensor (TOP33)
24/06 15:56:31 - SYSTEM: Heatpump is WAR mode (compensation curve)
24/06 15:56:31 - Function - SoftStart: 1
24/06 15:56:31 - Function Solar: 0
24/06 15:56:31 - Function NightReduction: 0
24/06 15:56:31 - SYSTEM - HEISHAMON Connection: Online
24/06 15:56:29 - SYSTEM - HEISHAMON Connection: Offline
24/06 15:56:21 - SYSTEM: Start---------------------------------------------------------------

Where do I find th debug screen?

**Comment by usauerbrey** [comment]
Or do you mean the debug of Node-red?

**Comment by usauerbrey** [comment]
The next restart was at 24/06 17:15:22 - SYSTEM: Start---------------------------------------------------------------
and the debug of node red shows:
24.6.2023, 17:12:57[node: Function - bucket 1 + 2 combined](https://dortmund.sby.net:1881/#)
function : (error)
"TypeError: Cannot read property 'payload' of undefined"
24.6.2023, 17:15:25[node: System check](https://dortmund.sby.net:1881/#)
function : (error)
"TypeError: Cannot read property 'on_off_active' of undefined"
24.6.2023, 17:15:26[node: Function - bucket 1 + 2 combined](https://dortmund.sby.net:1881/#)
function : (error)
"TypeError: Cannot read property 'payload' of undefined"
24.6.2023, 17:15:27[node: Load trigger](https://dortmund.sby.net:1881/#)
function : (error)
"TypeError: Cannot read property 'PumpMaxFlowSetting' of undefined"
24.6.2023, 17:15:28[node: Draw chart](https://dortmund.sby.net:1881/#)
function : (error)
"TypeError: Cannot read property 'detection_method' of undefined"
24.6.2023, 17:15:29[node: Draw chart](https://dortmund.sby.net:1881/#)
function : (error)
"TypeError: Cannot read property 'detection_method' of undefined"
24.6.2023, 17:15:30[node: Function RTC automation](https://dortmund.sby.net:1881/#)
function : (error)
"TypeError: Cannot read property 'function_active_state' of undefined"
24.6.2023, 17:15:31[node: Draw chart](https://dortmund.sby.net:1881/#)
function : (error)
"TypeError: Cannot read property 'detection_method' of undefined"
24.6.2023, 17:16:24[node: 2148ba5e64e1066d](https://dortmund.sby.net:1881/#)
msg : error
"Error: A 400 Bad Request error occurred: {"error":"unable to parse 'electricity,location=COP cop=NaN': invalid number"}↵"
24.6.2023, 17:16:25[node: 2148ba5e64e1066d](https://dortmund.sby.net:1881/#)
msg : error
"Error: A 400 Bad Request error occurred: {"error":"unable to parse 'electricity,location=COP cop=NaN': invalid number"}↵"
24.6.2023, 17:16:25[node: 2148ba5e64e1066d](https://dortmund.sby.net:1881/#)
msg : error
"Error: A 400 Bad Request error occurred: {"error":"unable to parse 'electricity,location=COP cop=NaN': invalid number"}↵"
24.6.2023, 17:16:25[node: 2148ba5e64e1066d](https://dortmund.sby.net:1881/#)
msg : error
"Error: A 400 Bad Request error occurred: {"error":"unable to parse 'electricity,location=COP cop=NaN': invalid number"}↵"
24.6.2023, 17:16:25[node: Draw chart](https://dortmund.sby.net:1881/#)
function : (error)
"TypeError: Cannot read property 'detection_method' of undefined"
24.6.2023, 17:16:25[node: DHW SP Manager](https://dortmund.sby.net:1881/#)
function : (error)
"TypeError: Cannot read property 'state' of undefined"
24.6.2023, 17:16:25[node: Function RTC automation](https://dortmund.sby.net:1881/#)
function : (error)
"TypeError: Cannot read property 'function_active_state' of undefined"
24.6.2023, 17:16:25[node: Function RTC automation](https://dortmund.sby.net:1881/#)
function : (error)
"TypeError: Cannot read property 'function_active_state' of undefined"
24.6.2023, 17:16:25[node: cee35b0a1e2da0ea](https://dortmund.sby.net:1881/#)
function : (error)
"TypeError: Cannot read property 'function_active_state' of undefined"

**Comment by edterbak** [comment]
Function Pump speed: Max pumpspeed set to undefined (NaN%) (Low)

This one is good to know. thanks.
I think the startup process for people with fresh setups needs to be checked if all is handled nicely. I will do that.

Question. 
Have you setup correctly the persistant storage? 

I would like to advice you to go into every tab of the functions and set values and toggles manually. 
WAR tab. 
Pumpspeed
RTC
COOL
Softstart
Solar2DHW

Start with all functions disabled.

**Comment by usauerbrey** [comment]
Have you setup correctly the persistant storage? 
I am not sure. I tried to do it like you installation hinta say, but it doent not work.
If I set softstart = ON, it is OFF again after a restart.

**Comment by edterbak** [comment]
I suspect the persistant storage is one problem. (it might not be the only one)

You have to figure out how to change the settings.js for Node Red. Make sure the contextStorage is working correct.

**Comment by edterbak** [comment]
![image](https://github.com/edterbak/NodeRed_Heishamon_control/assets/3155621/850ccbb4-937b-4b0c-9d0b-54ff9ac4b2c1)
Look into a [change] node. 
You need to see this "file" in the dropdown. If you do, it is good. If you dont... this needs your love :)

**Comment by usauerbrey** [comment]
indeed at least one of my problems is the persistant storage.
I found 11 files named settings.js in the system and 3 of them contained a section contextStorage. I change all 3 files to the correct content of contextStorage and rebooted the system. Nevertheless the check with the change node fails. 
I will investigate

**Comment by edterbak** [comment]
Did you get this sorted?

**Comment by usauerbrey** [comment]
Hi Ed
Sorrily not. I could not manage it to enable persistence storage in the Venus OS based Raspi system. So currently I am out of ideas.
Best Regards Uwe

**Comment by edterbak** [comment]
The raspberrys are getting back in stock.prices are lowering again.
You could pick up one and set it up with ssd drive as os disk.
Or if you have (like me) a home server, setup proxmox and run a linux system virtually.
Or if you have a NAS you might be able to run a docker container with a linux and setup node red in there.

Sorry to hear the venus os thing did not workout yet.
Is there a support page for users for it?

**Comment by usauerbrey** [comment]
Of course another Raspi ist a solution, but I am not very happy with it. I am going to make an own flow, which is very limited and does not use any persistence data at all. The graphs I need are genereated via graphana (on a different system on a different site anyhow)

**Comment by edterbak** [comment]
Good. Dont let yourself be stoppen by something like this. Just do it yourself. :)
This is the power of mqtt and the heishamon. 
Hope you get things as you want it soon.
