### ISSUE TITLE
[ENHANCEMENT]:DHW-Temperatur adjustable with Scheduler

### ISSUE THREAD

**Issue by WP-Rue** [edterbak/NodeRed_Heishamon_control#120]
**Is your feature request related to a problem or use case? Please describe.**
I use your Nodered Flow V23.0 since 4 weeks- first off all: thank you very much for your work!!!
I would like to reduce setpoint for DHW to shift operation time from night to day- because of higher outside temperatures and therefor better cop. I didn’t find a solution with the scheduler…?

Another question concerning the code: there are nodes (complete!) which are not looking at the end of any other node- in my imported flow: is that ok?

**Describe the solution you'd like**
Setpoint DHW in scheduler…
Thanks and have a nice holiday!
Greetings 
Rüdiger- lower Saxony, Germany

**Comment by edterbak** [comment]
thats a good idea. 
I will pick this up.

thanks !!!

**Comment by edterbak** [comment]
Done in v23.05
Ready for upload at your will. :)

**Comment by edterbak** [comment]
You can close this item if you think this is implemented and as requested

**Comment by WP-Rue** [comment]
Thanks for your ultra-fast response and reaction!! I will try within the next days an will report- not so fast as you...;-)

**Comment by WP-Rue** [comment]
V23.05 imported and deployed: will see if setting of DHW will work tonight. One feedback already: if you try to change the temperature of dhw SP in scheduler again, the window for adjusting don't open again: you have to choose any other action again first and than choose again dhw setpoint to get to the window to adjust the temperature...
And I reduce to 35 degree, because my sensor is 5 degrees to low😉

**Comment by WP-Rue** [comment]
In system log set setpoint DHW is visible- but no reaction of heatpump or in heishamon ( TOP 9: Target Temp DHW) - will have a look within next days and report here..

**Comment by WP-Rue** [comment]
For changing the temperature in function block "pupup" in flow "WP_Scheduler" I had to add some parseInt -e.g.:
 if (pay===undefined || **parseIn**t(pay) < 5) {pay=20} to avoid error.
I had problems with an old entry in the scheduler- maybe the update of an old entry in the scheduler-list to the new condition-feature didn't work perfect. But after deleting my old entry (from my previous version 23.02) and create a new one - the feature of adjusting DHW-target-temperature seems to work.
