### ISSUE TITLE
[BUG]: External room thermostat sets temperature shift.

### ISSUE THREAD

**Issue by Richard-Kroon** [edterbak/NodeRed_Heishamon_control#123]
Heatpump setting: Zone & sensor > sensor > Room thermostat.
When the heatpump is configured with a external room thermostat (in my case with CN2 on/off functionality)the node red flow is not working correctly. Changing the recommended water temp. seems to do nothing. 

Outlet setpoint is not changing and also WAR does not follow the curve.
logging ( Function WAR: RoomThermostat found or using Compensation curve. Using internal Panasonic WAR function. NodeRed WAR function is now disabled)

![node-red outlet setpoint](https://github.com/edterbak/NodeRed_Heishamon_control/assets/61867288/9d603af2-10d4-42bb-b8ed-91529112cf49)

![WAR heat shift](https://github.com/edterbak/NodeRed_Heishamon_control/assets/61867288/76c985b5-122a-40e4-8598-4ba36bd687bd)

**Comment by edterbak** [comment]
Hi Richard,

Can you help me fix this. 
Are you using Direct operating mode or Compensation Curve?

I would like a copy of all the data in your heishamon. 

Like so:

<html>
<body>


Topic | Name | Value | Description
-- | -- | -- | --
TOP0 | Heatpump_State | 1 | On
TOP1 | Pump_Flow | 20.54 | l/min
TOP2 | Force_DHW_State | 0 | Disabled
TOP3 | Quiet_Mode_Schedule | 0 | Disabled
TOP4 | Operating_Mode_State | 0 | Heat
TOP5 | Main_Inlet_Temp | 28 | °C
TOP6 | Main_Outlet_Temp | 30.25 | °C
TOP7 | Main_Target_Temp | 30 | °C
TOP8 | Compressor_Freq | 27 | Hz
TOP9 | DHW_Target_Temp | 52 | °C
TOP10 | DHW_Temp | 47 | °C
TOP11 | Operations_Hours | 8256 | hours
TOP12 | Operations_Counter | 8249 | count
TOP13 | Main_Schedule_State | 0 | Disabled
TOP14 | Outside_Temp | 8 | °C
TOP15 | Heat_Energy_Production | 3200 | Watt
TOP16 | Heat_Energy_Consumption | 600 | Watt
TOP17 | Powerful_Mode_Time | 0 | Off
TOP18 | Quiet_Mode_Level | 2 | Level 2
TOP19 | Holiday_Mode_State | 0 | Off
TOP20 | ThreeWay_Valve_State | 0 | Room
TOP21 | Outside_Pipe_Temp | 3 | °C
TOP22 | DHW_Heat_Delta | -5 | K
TOP23 | Heat_Delta | 2 | K
TOP24 | Cool_Delta | 1 | K
TOP25 | DHW_Holiday_Shift_Temp | -15 | K
TOP26 | Defrosting_State | 0 | Disabled
TOP27 | Z1_Heat_Request_Temp | 2 | °C
TOP28 | Z1_Cool_Request_Temp | 18 | °C
TOP29 | Z1_Heat_Curve_Target_High_Temp | 30 | °C
TOP30 | Z1_Heat_Curve_Target_Low_Temp | 26 | °C
TOP31 | Z1_Heat_Curve_Outside_High_Temp | 14 | °C
TOP32 | Z1_Heat_Curve_Outside_Low_Temp | -5 | °C
TOP33 | Room_Thermostat_Temp | 24 | °C
TOP34 | Z2_Heat_Request_Temp | 0 | °C
TOP35 | Z2_Cool_Request_Temp | 10 | °C
TOP36 | Z1_Water_Temp | -78 | °C
TOP37 | Z2_Water_Temp | -78 | °C
TOP38 | Cool_Energy_Production | 0 | Watt
TOP39 | Cool_Energy_Consumption | 0 | Watt
TOP40 | DHW_Energy_Production | 0 | Watt
TOP41 | DHW_Energy_Consumption | 0 | Watt
TOP42 | Z1_Water_Target_Temp | 30 | °C
TOP43 | Z2_Water_Target_Temp | 42 | °C
TOP44 | Error | No error | Error
TOP45 | Room_Holiday_Shift_Temp | -15 | K
TOP46 | Buffer_Temp | -78 | °C
TOP47 | Solar_Temp | -78 | °C
TOP48 | Pool_Temp | -78 | °C
TOP49 | Main_Hex_Outlet_Temp | 31 | °C
TOP50 | Discharge_Temp | 39 | °C
TOP51 | Inside_Pipe_Temp | 30 | °C
TOP52 | Defrost_Temp | -31 | °C
TOP53 | Eva_Outlet_Temp | 4 | °C
TOP54 | Bypass_Outlet_Temp | -31 | °C
TOP55 | Ipm_Temp | 21 | °C
TOP56 | Z1_Temp | 30 | °C
TOP57 | Z2_Temp | -128 | °C
TOP58 | DHW_Heater_State | 1 | Free
TOP59 | Room_Heater_State | 1 | Free
TOP60 | Internal_Heater_State | 0 | Inactive
TOP61 | External_Heater_State | 0 | Inactive
TOP62 | Fan1_Motor_Speed | 390 | r/min
TOP63 | Fan2_Motor_Speed | 0 | r/min
TOP64 | High_Pressure | 19.4 | Kgf/cm2
TOP65 | Pump_Speed | 3500 | r/min
TOP66 | Low_Pressure | 0 | Kgf/cm2
TOP67 | Compressor_Current | 2.8 | Ampere
TOP68 | Force_Heater_State | 0 | Inactive
TOP69 | Sterilization_State | 0 | Inactive
TOP70 | Sterilization_Temp | 62 | °C
TOP71 | Sterilization_Max_Time | 60 | Minutes
TOP72 | Z1_Cool_Curve_Target_High_Temp | 18 | °C
TOP73 | Z1_Cool_Curve_Target_Low_Temp | 10 | °C
TOP74 | Z1_Cool_Curve_Outside_High_Temp | 15 | °C
TOP75 | Z1_Cool_Curve_Outside_Low_Temp | 20 | °C
TOP76 | Heating_Mode | 0 | Comp. Curve
TOP77 | Heating_Off_Outdoor_Temp | 35 | °C
TOP78 | Heater_On_Outdoor_Temp | 0 | °C
TOP79 | Heat_To_Cool_Temp | 25 | °C
TOP80 | Cool_To_Heat_Temp | 20 | °C
TOP81 | Cooling_Mode | 1 | Direct
TOP82 | Z2_Heat_Curve_Target_High_Temp | 55 | °C
TOP83 | Z2_Heat_Curve_Target_Low_Temp | 35 | °C
TOP84 | Z2_Heat_Curve_Outside_High_Temp | 15 | °C
TOP85 | Z2_Heat_Curve_Outside_Low_Temp | -5 | °C
TOP86 | Z2_Cool_Curve_Target_High_Temp | 10 | °C
TOP87 | Z2_Cool_Curve_Target_Low_Temp | 10 | °C
TOP88 | Z2_Cool_Curve_Outside_High_Temp | 30 | °C
TOP89 | Z2_Cool_Curve_Outside_Low_Temp | 20 | °C
TOP90 | Room_Heater_Operations_Hours | 66 | hours
TOP91 | DHW_Heater_Operations_Hours | 151 | hours
TOP92 | Heat_Pump_Model | 20 | WH-MDC07J3E5
TOP93 | Pump_Duty | 140 | Duty
TOP94 | Zones_State | 0 | Zone1 active
TOP95 | Max_Pump_Duty | 140 | Duty
TOP96 | Heater_Delay_Time | 30 | Minutes
TOP97 | Heater_Start_Delta | -5 | K
TOP98 | Heater_Stop_Delta | 0 | K
TOP99 | Buffer_Installed | 0 | Disabled
TOP100 | DHW_Installed | 1 | Enabled
TOP101 | Solar_Mode | 0 | Disabled
TOP102 | Solar_On_Delta | 10 | K
TOP103 | Solar_Off_Delta | 5 | K
TOP104 | Solar_Frost_Protection | 5 | °C
TOP105 | Solar_High_Limit | 80 | °C
TOP106 | Pump_Flowrate_Mode | 0 | DeltaT
TOP107 | Liquid_Type | 0 | Water
TOP108 | Alt_External_Sensor | 0 | Disabled
TOP109 | Anti_Freeze_Mode | 1 | Enabled
TOP110 | Optional_PCB | 0 | Disabled
TOP111 | Z1_Sensor_Settings | 0 | Water Temperature
TOP112 | Z2_Sensor_Settings | 0 | Water Temperature
TOP113 | Buffer_Tank_Delta | 5 | K
TOP114 | External_Pad_Heater | 0 | Disabled


</body>
</html>

**Comment by Richard-Kroon** [comment]
Hi edterbak,

When the heatpump is configured with a external room thermostat I can choose both, direct mode or Compensation Curve.
I use Direct mode, but heatshifting is not possible when using the thermostat setting.

all the data in heishamon with the Heatpump setting: Zone & sensor > sensor > Room thermostat.

TOP0	Heatpump_State	1	On
TOP1	Pump_Flow	0.13	l/min
TOP2	Force_DHW_State	0	Disabled
TOP3	Quiet_Mode_Schedule	0	Disabled
TOP4	Operating_Mode_State	3	DHW
TOP5	Main_Inlet_Temp	24.75	°C
TOP6	Main_Outlet_Temp	24.75	°C
TOP7	Main_Target_Temp	29	°C
TOP8	Compressor_Freq	0	Hz
TOP9	DHW_Target_Temp	45	°C
TOP10	DHW_Temp	55	°C
TOP11	Operations_Hours	4809	hours
TOP12	Operations_Counter	5483	count
TOP13	Main_Schedule_State	0	Disabled
TOP14	Outside_Temp	13	°C
TOP15	Heat_Energy_Production	0	Watt
TOP16	Heat_Energy_Consumption	0	Watt
TOP17	Powerful_Mode_Time	0	Off
TOP18	Quiet_Mode_Level	0	Off
TOP19	Holiday_Mode_State	0	Off
TOP20	ThreeWay_Valve_State	0	Room
TOP21	Outside_Pipe_Temp	12	°C
TOP22	DHW_Heat_Delta	-10	K
TOP23	Heat_Delta	4	K
TOP24	Cool_Delta	5	K
TOP25	DHW_Holiday_Shift_Temp	-15	K
TOP26	Defrosting_State	0	Disabled
TOP27	Z1_Heat_Request_Temp	0	°C
TOP28	Z1_Cool_Request_Temp	0	°C
TOP29	Z1_Heat_Curve_Target_High_Temp	29	°C
TOP30	Z1_Heat_Curve_Target_Low_Temp	35	°C
TOP31	Z1_Heat_Curve_Outside_High_Temp	15	°C
TOP32	Z1_Heat_Curve_Outside_Low_Temp	-5	°C
TOP33	Room_Thermostat_Temp	24	°C
TOP34	Z2_Heat_Request_Temp	35	°C
TOP35	Z2_Cool_Request_Temp	0	°C
TOP36	Z1_Water_Temp	-78	°C
TOP37	Z2_Water_Temp	-78	°C
TOP38	Cool_Energy_Production	0	Watt
TOP39	Cool_Energy_Consumption	0	Watt
TOP40	DHW_Energy_Production	0	Watt
TOP41	DHW_Energy_Consumption	0	Watt
TOP42	Z1_Water_Target_Temp	29	°C
TOP43	Z2_Water_Target_Temp	35	°C
TOP44	Error	No error	Error
TOP45	Room_Holiday_Shift_Temp	-15	K
TOP46	Buffer_Temp	-78	°C
TOP47	Solar_Temp	-78	°C
TOP48	Pool_Temp	-78	°C
TOP49	Main_Hex_Outlet_Temp	25	°C
TOP50	Discharge_Temp	20	°C
TOP51	Inside_Pipe_Temp	24	°C
TOP52	Defrost_Temp	0	°C
TOP53	Eva_Outlet_Temp	14	°C
TOP54	Bypass_Outlet_Temp	0	°C
TOP55	Ipm_Temp	16	°C
TOP56	Z1_Temp	24	°C
TOP57	Z2_Temp	-128	°C
TOP58	DHW_Heater_State	1	Free
TOP59	Room_Heater_State	1	Free
TOP60	Internal_Heater_State	0	Inactive
TOP61	External_Heater_State	0	Inactive
TOP62	Fan1_Motor_Speed	0	r/min
TOP63	Fan2_Motor_Speed	0	r/min
TOP64	High_Pressure	11.4	Kgf/cm2
TOP65	Pump_Speed	0	r/min
TOP66	Low_Pressure	0	Kgf/cm2
TOP67	Compressor_Current	0.0	Ampere
TOP68	Force_Heater_State	0	Inactive
TOP69	Sterilization_State	0	Inactive
TOP70	Sterilization_Temp	62	°C
TOP71	Sterilization_Max_Time	5	Minutes
TOP72	Z1_Cool_Curve_Target_High_Temp	15	°C
TOP73	Z1_Cool_Curve_Target_Low_Temp	10	°C
TOP74	Z1_Cool_Curve_Outside_High_Temp	30	°C
TOP75	Z1_Cool_Curve_Outside_Low_Temp	20	°C
TOP76	Heating_Mode	1	Direct
TOP77	Heating_Off_Outdoor_Temp	20	°C
TOP78	Heater_On_Outdoor_Temp	-5	°C
TOP79	Heat_To_Cool_Temp	15	°C
TOP80	Cool_To_Heat_Temp	10	°C
TOP81	Cooling_Mode	0	Comp. Curve
TOP82	Z2_Heat_Curve_Target_High_Temp	35	°C
TOP83	Z2_Heat_Curve_Target_Low_Temp	35	°C
TOP84	Z2_Heat_Curve_Outside_High_Temp	15	°C
TOP85	Z2_Heat_Curve_Outside_Low_Temp	-5	°C
TOP86	Z2_Cool_Curve_Target_High_Temp	15	°C
TOP87	Z2_Cool_Curve_Target_Low_Temp	10	°C
TOP88	Z2_Cool_Curve_Outside_High_Temp	30	°C
TOP89	Z2_Cool_Curve_Outside_Low_Temp	20	°C
TOP90	Room_Heater_Operations_Hours	105	hours
TOP91	DHW_Heater_Operations_Hours	288	hours
TOP92	Heat_Pump_Model	18	IDU: WH-SDC0709J3E5, ODU: WH-UD07JE5
TOP93	Pump_Duty	0	Duty
TOP94	Zones_State	0	Zone1 active
TOP95	Max_Pump_Duty	197	Duty
TOP96	Heater_Delay_Time	30	Minutes
TOP97	Heater_Start_Delta	-4	K
TOP98	Heater_Stop_Delta	-2	K
TOP99	Buffer_Installed	0	Disabled
TOP100	DHW_Installed	1	Enabled
TOP101	Solar_Mode	0	Disabled
TOP102	Solar_On_Delta	10	K
TOP103	Solar_Off_Delta	5	K
TOP104	Solar_Frost_Protection	5	°C
TOP105	Solar_High_Limit	80	°C
TOP106	Pump_Flowrate_Mode	0	DeltaT
TOP107	Liquid_Type	0	Water
TOP108	Alt_External_Sensor	0	Disabled
TOP109	Anti_Freeze_Mode	1	Enabled
TOP110	Optional_PCB	0	Disabled
TOP111	Z1_Sensor_Settings	0	External Thermostat
TOP112	Z2_Sensor_Settings	0	Water Temperature
TOP113	Buffer_Tank_Delta	5	K
TOP114	External_Pad_Heater	0	Disabled

**Comment by edterbak** [comment]
`TOP111 Z1_Sensor_Settings 0 External Thermostat`

That does not look right... 
Can you please do the change of the setting, and wait for 2 minutes to make sure all values come in heishamon, then do the copy past.?

**Comment by edterbak** [comment]
I uploaded v23.10 beta9. It should be improving on this problem ... a lot.
Hope you can confirm.

**Comment by edterbak** [comment]
Hi @Richard-Kroon 

Can you retest the latest beta v32, to see if this latest version solves the reported issues?

**Comment by Richard-Kroon** [comment]
Hi @edterbak 

I'm using beta v31 for a while now, basic functionality works great and i'm very happy with it.
Will start testing v32 staring today and let you know if there are any issues.

**Comment by edterbak** [comment]
I haver released v24.00 stable

It contains the same logic as in beta 32. So if you do not have any issues anymore with this beta 32 version, can you please close this issue?

**Comment by edterbak** [comment]
@Richard-Kroon 
It would be nice if you can confirm this issue to be fixed 😄
