### ISSUE TITLE
DegreeDays - question

### ISSUE THREAD

**Issue by nofeardh** [edterbak/NodeRed_Heishamon_control#129]
Hi,

I have one question about DegreeDays chart - I suppose green bars should be outside temperature? In my case (using Aquarea outside temp sensor) those values are much lower than actual values. What could be wrong?

![image](https://github.com/edterbak/NodeRed_Heishamon_control/assets/66254281/3d378d64-15c3-465b-b725-dce92b6eaaee)

And congratulations for whole project!!

Kind regards,
Aljosa

**Comment by nofeardh** [comment]
Sorry....I just found info what DegreeDays is all about :)

**Comment by edterbak** [comment]
Haha . Hi.
Yes. You already found out. 
Degree days is somewhat counter intuitive. 
Maybe after reading your question, adding a little text to explain could be useful. Thanks for taking the effort to post your question here instead of dwelling on it...  
Regards.
