### ISSUE TITLE
[ENHANCEMENT]: Anti-Theft request

### ISSUE THREAD

**Issue by WP-Rue** [edterbak/NodeRed_Heishamon_control#130]
Is their a possibility to generate some kind of watchdog to pevent theft?
Some kind of signal in node-red to switch lamps, horns or send emails would be good.
In Germany are reports about stealing of heatpumps...
..and it could be easy with node-red to check the connection to the panasonic heatpump...

Greetings Rue
(actual first heating hours with 23.09)

**Comment by edterbak** [comment]
# Instruction:

The heishamon sends a signal 'Online' every 5/10 seconds. Or 'Offline' if the pump is offline.
The 'Offline' command is used to start a timer.
The timer is reset again if a 'Online' message is coming in again.

The timer is currently set to 5 minutes.

After 5 minutes, the output of the node is string text 'ALARM'. 

You can use this as trigger elsewhere in node red.

**Comment by WP-Rue** [comment]
Wonderful- I reduce time to 1 min and will give it a try..
At first Signal goes to simple LED on display in kitchen and email- to check, if there are false alarms. If ok, I plan to switch on lamps outside and maybe send the alarm signal to the Philipps hue system (red flashing)..
But I think the alarm has to switch of during reboot Heishamon..!?

Yes - hopefully I never need this.

**Comment by edterbak** [comment]
I think 1 minute is a little optimistic :) 
But you just have to see if you end up with a disco or not ghehehe :)
Adjust where needed ofcourse

**Comment by edterbak** [comment]
You can close the card if the solution is okay

**Comment by WP-Rue** [comment]
Up to now no false alarm- with 1min!
Thanks!
