### ISSUE TITLE
Settings memory

### ISSUE THREAD

**Issue by mniszek** [edterbak/NodeRed_Heishamon_control#133]
Hi.  Sorry if this has already been asked but I couldn't find anything.  After each restart of Home Assistant (power off/power on), I have to set everything again.  Any set temperature or whatever.  Sometimes the system doesn't turn off for a week or more, but sometimes there are power outages.  Is there an option somewhere to save what is set in the GUI?

**Comment by edterbak** [comment]
Hi, 

This is a weird issue. 
I assume you are running HomeAssistent and have Node-Red installed as a HA Add-on right?
Dit you set persistent storage in settings.js like described here?
https://github.com/edterbak/NodeRed_Heishamon_control/tree/main/HomeAssistant

If you are not running Node REd in HA, then you must arrange the correct memory storage in the settings.js file.
More about this can be found in github page.

https://github.com/edterbak/NodeRed_Heishamon_control#b---adjust-settingsjs

**Comment by mniszek** [comment]
Unbelievable :/ I didn't save the changes to the settings.js file.  Well, I'm an idiot.  Everything works great.  Thank you.
