### ISSUE TITLE
[BUG]: Softstart jumps between 2 temperatures

### ISSUE THREAD

**Issue by mabek** [edterbak/NodeRed_Heishamon_control#135]
**Describe the bug**
Hi, Softstart jumps between 2 temperatures in my case and then MQTT commands are blocked. Look at the screenshot, it all happend withing fractions of a second.

See Screenshot
![C882850F-CAFA-42AD-82D3-408EF1051FBB](https://github.com/edterbak/NodeRed_Heishamon_control/assets/7482652/9b6fe07c-2a4f-4b06-ba7d-6a9709c9899d)

**Additional context**

============================================================
NightReductionRoomSetpoint.NORMAL: 20
NightReductionRoomSetpoint.LOW: 18
NightReduction room_setpoint.state: 0
---------------------------------------------------------------------------------------------------
F_NR_correction: 0
NightReductionWaterTemp.current_value: 0
NightReductionWaterTemp.correction: 0
NightReductionWaterTemp.state: undefined
---------------------------------------------------------------------------------------------------
F_ReducePumpSpeed.state: 0
F_ReducePumpSpeed.LowSpeed: 178
F_ReducePumpSpeed.NormalSpeed: undefined
F_ReducePumpSpeed.PumpMaxFlowSetting: 151
---------------------------------------------------------------------------------------------------
MQTT.block_mode_previous: BLOCK ALL
MQTT.block_mode: BLOCK ALL
MQTT.message_limit: 610
MQTT.counter: 2842 (total)
MQTT.messages_yesterday: 162
MQTT.messages_today: 2286
MQTT.allow_scheduler: 1
MQTT.allow_solar: 0
MQTT.allow_rtc_onoff: 0
MQTT.block_active: 1
---------------------------------------------------------------------------------------------------
Function - SoftStart Quietmode is disabled
---------------------------------------------------------------------------------------------------
Actual runtime: 0 minutes, last runtime: 20 minutes
SoftStart TimeElapsed: 0 (waiting for next run)
F_SS_upperlimit_correction: 2°C (Max. setpoint increase)
F_SS_total_duration: 2700 minutes (Max. time the SoftStart will be active)
Function - SoftStart is enabled
---------------------------------------------------------------------------------------------------
The compressor has started 14 times in the last 24 hours
Highest compressor frequency ever recorded: 48 Hz
Total hours: 72, starts: 131, average runtime: 0.55 hours
Total Defrosts: 0, today 0, yesterday 0
Total MQTT-Commands send: 2842, today 2286, yesterday 162
---------------------------------------------------------------------------------------------------
RTC Room setpoint 20°C
F_RTC.incremental_setpoints_state: 0
F_RTC.F2_OM_state: 0 (RTC allow change OM is disabled)
F_RTC.F1_power_state: 0 (RTC turn heat on/off is disabled)
F_RTC.state: 0 (Function RTC is disabled)
F_RTC.on_off_status: undefined
F_RTC.on_off_active: 0
---------------------------------------------------------------------------------------------------
Schedule_1 on, Select,Monday,Tuesday,Wednesday,Thursday,Friday,Saturday,Sunday, 08:00, OperationMode0 (override)
Schedule_2 Warmwasser, Select,Monday,Tuesday,Wednesday,Thursday,Friday,Saturday,Sunday, 13:00, OperationMode3 (override)
Schedule_4 Heizen, Select,Monday,Tuesday,Wednesday,Thursday,Friday,Saturday,Sunday, 14:00, OperationMode0 (override)
Schedule_5 Aus, Select,Monday,Tuesday,Wednesday,Thursday,Friday,Saturday,Sunday, 20:00, HP_turn_off
Scheduler: 4 tasks are currently active
F_stored_next_operating_mode: undefined (ok)
F_SOLAR.function_active_state: undefined
solar_block_scheduler: undefined (ok)
---------------------------------------------------------------------------------------------------
No 1-wire sensors connected to Heishamon
No custom kWh-devices detected
Total errors: 0, last error: No error
MQTT-Commands: Are blocked (disable switch to unblock)
This flow is running for 22 hours without a restart.
SYSTEM Heatpump is in DIRECT mode
SYSTEM: Persistent storage is configured correctly
Target=31°C, Inlet=30.25°C, Outlet=30.25°C, Freq=0 Hz, Quiet mode=0, 0 Watt
HP power is on, operation mode Heat only, threeway valve in position Room
*SYSTEM: MQTT-Commands are blocked, this flow will not function correctly.
============================================================

**Comment by edterbak** [comment]
Hi, 
Not a good issue to read. 
It looks like it could be possible another program is trying to change settings.
 Could it be you have HomeAssistant running and also installed the heishamon comunity plugin/integration?
If so, In HomeAssistant, you need to go to the "Automations" tab and disable all automations related to heishamon 

If you disable the SoftStart function, does it work okay ?
First start the flow, and do not use any of the functions. 
If you manually set the water temperature, does this get accepted normally then?

Can you do a restart of node-red and disable the MQTT block again to see what happens. 

Regards.
