### ISSUE TITLE
RTC power trigger dT question

### ISSUE THREAD

**Issue by nofeardh** [edterbak/NodeRed_Heishamon_control#137]
**Describe the bug**
RTC action Turn Off/on power - action waiting for trigger dT

Hi,

I'm trying to understand RTC action "Turn Off/on power". I set above/below dT as you can see on the screenshot. In specific situation actual room temp was almost 0.4 C lower than Room setpoint, , compresor OFF, but workflow is still in "Waiting for trigger dT" status. What does this means and how this trigger dT is calculated? When should compressor goes ON in that specific situation?

Is it possible that this function gets somehow "interrupted" by some other action like "Force DWH" action or manual pump off action? is this a toggle action or specific ON/OFF command?

![TriggerDt](https://github.com/edterbak/NodeRed_Heishamon_control/assets/66254281/c62f7a0d-2b01-4f33-9beb-fefef18cedc0)

Many many thanks again for your fantastic workflow!! 

Kind regards,
Aljosa

**Comment by edterbak** [comment]
Hi, 

The rtc function will execute the action when the room temperature goes over the 0,5C above the setpoint. 
The action van be to turn off the heat pump.

Then when the temperature drops again below the -0,3 than the setpoint, the action will be reversed. So the heat pump wil be turned on again.

This function is only turning on off the heat pump or changing the operation mode.

It will not tell the Panasonic to turn on the compressor itself. This is only done by the internal logic of the pump itself.

Internal logic is;
Main outlet 4C below setpoint, turn on compressor.
Main outlet for more than 3 minutes, 2C above setpoint, turn off compressor

**Comment by edterbak** [comment]
Indeed. If a scheduled action like forceDHW is run in the mean time, this will (should) reset the rtc function.

**Comment by nofeardh** [comment]
Yes you're right! I totally forgot on this internal Panasonic logic for compressor on/off control.
