### ISSUE TITLE
[ENHANCEMENT]: table with supported Heishamon versions on Github. 

### ISSUE THREAD

**Issue by dennisbakhuis** [edterbak/NodeRed_Heishamon_control#139]
First of all, many thanks for this awesome project. My experience with these flows, together with Heishamon, and my Panasonic T-CAP MXC12J9 were plug-and-play. In Dutch I would say, rotates as a tiny sun ;-) 

After a few weeks, my home assistant instance got a message on my Heishamon integration, saying that there is a firmware update (3.20). My first step was checking the change-log and I noticed that some topics got a rename. Next stop, checking if there would be any problems with the NodeRed flows. This was not so obvious, so I waited with the upgrade.

So the enhancement is actually, quite simple: have for each version of the NodeRed flows an accommodating/tested version of Heishamon. This can be a line with the version itself or a table style thing, not sure what is best. 

Maybe you are already using firmware version 3.20 of Heishamon. I am not sure if the change of power and energy gives any trouble, but a small confirmation would be great. 

What do you think?

**Comment by geduxas** [comment]
Truly version is 3.2, for now it's already 3.2.3. In 3.2 \*\_energy\_\* renamed to \*\_power\_\* also introduced extra topic for new K/L pump. And from 3.2.3 extra power topic's renamed to get end of \_Extra
Also from 3.2.3 heishamon wil send it's version number. It could be used to track for update.

**Comment by edterbak** [comment]
Thank you 
Most items are already in the(not so stable) beta. 
I will check the latest firmware again soon.

**Comment by dennisbakhuis** [comment]
Thanks a lot for both your responses.

Just to emphasize, I am just looking for some sort of written confirmation on Github of which version of the NR flows work with what version of Heishamon.

Example: 
Version 23{.09}
Compatible with Heishamon from 3.0 up to 3.1

I do not mind not updating or missing out on some features. But I do not want to loose valuable wife-appreciations credits due to the heating not working, after an update :-).

**Comment by geduxas** [comment]
@dennisbakhuis node-red uses basic home assistant functions, basically they will not change or get updated.. because almost everything is already done in heishamon..  now after appeared k/l series pumps, they have some extra sensors.. power consumption/production become more detailed, so panasonic had moved it to other location. Appeared digital pressure sensor.. Don't know if it required to node-red.. also appeared second inlet water sensor.. Also don't know any use cases hera.. so I thin there is no point tie node-red to heishamon version.

**Comment by edterbak** [comment]
It is little trouble to mention something about heishamon firmware versions.  :)

**Comment by edterbak** [comment]
Just as an update, to indicate the hidden importance of this issue...

In the latest beta's I am using TOP111 and TOP112. 
It turns out this topic is only available after 3.0 or 3.1. 

So, having this information clear up front for users is important. 
I have just added this information on the main github page as a "ATTENTION!" on top about the beta's. 

As soon as the current work on the beta's is mature enough to be called stable, I will make this piece of information more clear in the readme.md

Thanks @dennisbakhuis

**Comment by edterbak** [comment]
Thank you for the link.

Background story for me is that i only updated to 3.1 four months ago. 
Recently to 3.2.
Just the last two weeks i have discovered the use of top111 and top112. Using it now in the beta.

So now the firmware function has become a point of attention for the flow. 😄

**Comment by geduxas** [comment]
> Thank you for the link.
> 
> Background story for me is that i only updated to 3.1 four months ago. Recently to 3.2. Just the last two weeks i have discovered the use of top111 and top112. Using it now in the beta.
> 
> So now the firmware function has become a point of attention for the flow. 😄

Ok, so for that purpose, i think if topic is missisng integration should shout about old firmware and urge for update.. and from 3.2.2 heishamon will print it's firmware version in stats.. so it will be easier to determinate version..

**Comment by edterbak** [comment]
Lol.. i just built that functionality.
Timmer for 10 minutes. If no top111 came in. Log entry with firmware info.

**Comment by dennisbakhuis** [comment]
Glad I could help. A rename of topics seemed it could have at least a minor influence. 

> Where did you find the changelog?

I just looked on the release page of Heishamon for version 3.2:
https://github.com/Egyras/HeishaMon/releases/tag/v3.2

**Comment by edterbak** [comment]
> .. and from 3.2.2 heishamon will print it's firmware version in stats.. so it will be easier to determinate version..

That sounds like a very good addition to the heishamon fw. Great work on heishmon @geduxas  😄  Awesome

**Comment by edterbak** [comment]
@dennisbakhuis 
Thank for this link. I found the answer I was looking for thanks to this link. Sometimes I struggle with github finding my way. It is not extremely intuitive. The link helped.

**Comment by dennisbakhuis** [comment]
Just a confirmation for other people who are looking for this information:
The node-red-flows (NRF) version 23.09 are compatible with Heishamon version <=3.1.

When upgrading Heishamon to 3.2.{0, 3} there is a rename in topics which is not compatible with NRF 23.09:
```
TOP15: "Heat_Energy_Production" —> "Heat_Power_Production",
TOP16: "Heat_Energy_Consumption" —> "Heat_Power_Consumption"
TOP40: "DHW_Energy_Production" —> "DHW_Power_Production"
TOP41: "DHW_Energy_Consumption" —> "DHW_Power_Consumption"
```

While I expect that NRF 23.09 will still be happy in running your HP, the information on energy/COP will probably be missing. So if you want to stay on the currently stable NRF 23.09, do not upgrade Heishamon and stay on version 3.1 or rename the topics manually.

**Comment by edterbak** [comment]
Hi. 
I added both node topics in de beta.
If one topic does not produce a value, it is the other topic.
Compatible

**Comment by edterbak** [comment]
I have changed the stored RTC variable names like this.

![image](https://github.com/edterbak/NodeRed_Heishamon_control/assets/3155621/29a6dba1-1ec7-427e-935a-efa0798ca7ab)

**Comment by edterbak** [comment]
The information about the firmware is on the front page on the top in v24.00 text.
For now I think this is sufficient. 

If this is incorrect, please give feedback on this then.
Otherwise, could you close the issue?

**Comment by dennisbakhuis** [comment]
Sorry, I did not realize I had to close this.
This all looks great! Thanks again!
