### ISSUE TITLE
WAR RTC Softstart T_outside is not defined

### ISSUE THREAD

**Issue by timovd** [edterbak/NodeRed_Heishamon_control#14]
I'm using TOP14 (Panasonic's internal temperature sensor) to define the outside temperature (last paragraph of https://github.com/edterbak/NodeRed_Heishamon_control#how-to-install-the-nr-flows).
Currently the outdoor temperature is 10 C. This should result in an outlet water temperature of 31,9 C.
In the NodeRed container I'm getting a lot of the same error messages;
_3 Jan 13:56:10 - [error] [function:WAR + RTC + Softstart function] ReferenceError: T_outside is not defined (line 179, col 23)_
This error occurs when enabling softstart. HEAT SP lower and upper limit are defined.
On the home screen it show's a Ta (SP) of 35. Shouldn't this be 32 C (rounded up) here? The actual outlet temperature is around 34 C.

            if (isNaN(T_outside))               // if the variable is Not a Number, produce an error message.

Could it be that there's an issue with a lot of decimals in a number?

**Comment by edterbak** [comment]
I found this bug.
It should be fixed in v10.
Can you confirm?

**Comment by edterbak** [comment]
Go to nodered flows
Tab WP control
In the purple , function: war+rtc+softstart function. Double click it so it opens.
Line 179, change it like this. The part between brackets was wrong to point to T_outside, which is not a variable.


            if (isNaN(ss_Tb))               // if the variable is Not a Number, produce an error message.

**Comment by edterbak** [comment]
But, beside this bug. Do not use the softstart funtion.
It results in irratic behavior an stops propper heating.

Need to fix softstart soon

**Comment by timovd** [comment]
Was still using V8. Doesn't occur anymore in v10.
