### ISSUE TITLE
[ENHANCEMENT]: Delay for outside Temp-Sensor

### ISSUE THREAD

**Issue by WP-Rue** [edterbak/NodeRed_Heishamon_control#140]
My idea is to delay the outside temperature sensor with a simple delay node and put it into custum sensor. My first attempt is with 4 hours.
If it is getting colder e.g. at night the delay results in later increasing of outlet setpoint due to WAR-function. If it is getting warmer outside the heatpump stays  longer at higher setpoint but works at higher outside temp with better efficiency. So the heat capacity of the house helps to increase the efficiency: longer time at lower power if it is getting colder and longer higher power at warmer outside temperatures.
Is that right- or am I wrong?
I will upload the flow tomorrow..

![image](https://github.com/edterbak/NodeRed_Heishamon_control/assets/140204844/34196a64-d798-4dda-812b-6ddfa3f53e65)

**Comment by WP-Rue** [comment]
[flows(59).json](https://github.com/edterbak/NodeRed_Heishamon_control/files/13325606/flows.59.json)

first providing the undelayed temp value and after e.g. 4h the output of the function node is switching to the delayed value...(due to 7200sec timeout in the V23.09 flow...

**Comment by edterbak** [comment]
Hi
In your personal tab where the signal is coming in. You can add a delay directly after that and then send the value to the rest of the flow (wp input)

This might be more than sufficient enough for you
😄

**Comment by edterbak** [comment]
What is your solution in the end?
My suggestion or something else?

**Comment by WP-Rue** [comment]
Dear Ed ter bak,wondering about you question: I posted my flow on github.In the mean point it it a simply delay node- as you suggested..But- I‘m not sure, if your flow, which has a 7200sec timeout for the custom outside temperature sensor is switching after 4h or more automatically from build in to custom sensor input…Therefore my solution is a function node which detects after deploy the for 4h missing (delayed) value and puts out the undelayed value until the delayed is available…And in moment this function node is in my personal area… so no problem!I‘m still thinking about the“Dau“-menue… and will come back with a proposal…And is their any further help available for softstart?? Sometimes I have 3-4min runs at night at higher temperatures (around 8-10 C)…Wish you a good start into the next week!Greetings from BrunswiekRüdiger Gesendet mit der GMX Mail AppAm 19.11.23 um 14:08 schrieb Ed ter Bak
                
            
            
                
                    Von: "Ed ter Bak" ***@***.***>Datum: 19. November 2023An: "edterbak/NodeRed_Heishamon_control" ***@***.***>Cc: "State change" ***@***.***>,"WP-Rue" ***@***.***>Betreff: Re: [edterbak/NodeRed_Heishamon_control] [ENHANCEMENT]: Delay for outside Temp-Sensor (Issue #140)
                
                
What is your solution in the end?
My suggestion or something else?
