### ISSUE TITLE
[ENHANCEMENT]:  Panel integrated temp sensor as trigger

### ISSUE THREAD

**Issue by sabom2d** [edterbak/NodeRed_Heishamon_control#141]
Hi Ed,

I just had a rough day, because one of my HP did not accept a higher value then 30° for Heating temperature.
I did not realize that I created that issue myself, because I switched from water temperature sensor to room temperature sensor for trigger of heat mesurement. And that accepts max. 30°

So when I set water temperture to 35, final wt always stayed at 30°.
Only now that I saw my mistake and switched back to Water temp. senosr NR accepts only 30°.

Maybe I overread it in the description, if not I would reccomend to add a hint in the description regarding the right sensor settings or maybe if possible add the function to the code to filter the setting of the configured sensor.

Regards

ede

**Comment by edterbak** [comment]
Thanks for you report!!!

Can you tell me exactly what the situation is?
Direct or Compensation curve?

In thermostat-mode: Where did you try to change the water setpoint to 35? in the flow or on the controller?

After going back to WaterTemp-mode: you changed the temperature in NR flow or Controller?

Can you check these values for me inside heishamon:
TOP29 | Z1_Heat_Curve_Target_High_Temp | 29
TOP30 | Z1_Heat_Curve_Target_Low_Temp | 25
TOP31 | Z1_Heat_Curve_Outside_High_Temp | 14
TOP32 | Z1_Heat_Curve_Outside_Low_Temp | -5

Thanks 😄

**Comment by sabom2d** [comment]
Hi Ed,

will try to answer your questions, below:

> Can you tell me exactly what the situation is? Direct or Compensation curve?
-Direct mode, as you mentioned in our former discussion
 
>In thermostat-mode: Where did you try to change the water setpoint to 35? in the flow or on the controller?> 
I changed the Sensor in the Control Panel, ( switch from Water to Inhouse  sensor )
after that the _Outlet Setpoint_  temperature in the Home Dashboard under _Heat pump_ - _Water temperature_ was fixed to 30°, the same was the value for the _Final water temperature_ in the HEAT Panel.
I tried to change the value unter _Water temp._ in the area _HEAT_.

> After going back to WaterTemp-mode: you changed the temperature in NR flow or Controller?
After I realized my mistake I changed the fixed Temperature in the Control Panel to 35 degrees and to check if your NR-Flow now was working as expected, I changed the temperatur in the NR flow unter HEAT to 32. Directly after that the former fixed values also changed from 35 to 32, so now everything is ok again. Configured Temperature is still 32°.
 
> Can you check these values for me inside heishamon: 
TOP29 | Z1_Heat_Curve_Target_High_Temp | 29      My Value Now:32
TOP30 | Z1_Heat_Curve_Target_Low_Temp | 25       My Value Now:35
TOP31 | Z1_Heat_Curve_Outside_High_Temp | 14   My Value Now:15
TOP32 | Z1_Heat_Curve_Outside_Low_Temp | -5     My Value Now:-5

I'm not sure, if it is even possible via Heishamon, to recognize whish sensor is defined in the Control Panel as Trigger Sensor.
Maybe it's not even possible to check in your Flow. So if it's not possible I would recommend to give a HInt to not change the Main trigger sensor in the Control Panel, although it was still my own mistake, that led to the missinterpretion.

Thanks again for your tool, which helps me a lot to get my HP running as efficient as possible.


regards

ede

**Comment by edterbak** [comment]
What version flow are you using?
23.09 or the latest beta 23.10 beta31?

The last version, the beta31, is working nicely with this situation. (it should, tested it for weeks now) 
I suggest you update it to get it working with direct/thermostat. 

If the issue is not solved with beta31, I can fix it there.

**Comment by sabom2d** [comment]
Hi Ed,

ok, did not know this. OK then I have to think about upgrading.
Thanks.
