### ISSUE TITLE
[BUG]: Tsp sometimes jumps to "set water temperature" and not applying "custom functions"

### ISSUE THREAD

**Issue by dennisbakhuis** [edterbak/NodeRed_Heishamon_control#142]
**Describe the bug**
While most of the time the system works nicely, occasionally (few times a day), the Tsp jumps from its corrected value with WAR and RTC to the value without "custom functions", which is of course much higher. This is only for a short while (few minutes) until it jumps back to the expected Tsp with all "custom functions" applied.

**To Reproduce**
Pump: WH-MXC12J9E8
Heishamon: 3.1
NR-flows: 23.09
Mode: only heat
Functions: WAR, RTC, Softstart

**Expected behavior**
These jumps are not normal and make the pump start for short while. This is of course not what we want.

**Screenshots**
I noticed it first in my hass dashboard to glance if all is ok (Here also Softstart is applied which adds the addtional wiggle):
<img width="1202" alt="Screenshot 2023-11-15 at 08 46 16" src="https://github.com/edterbak/NodeRed_Heishamon_control/assets/24434212/99309856-a98e-4f36-aab2-cd4f4f6ea256">

This is also clearly seen in the NRui dashboard:
<img width="1008" alt="Screenshot 2023-11-15 at 08 48 23" src="https://github.com/edterbak/NodeRed_Heishamon_control/assets/24434212/45130c04-65f7-4c0d-8122-7f975a7d2977">

I do not see anything weird in the WAR temperatures in NRui:
<img width="577" alt="Screenshot 2023-11-15 at 08 51 02" src="https://github.com/edterbak/NodeRed_Heishamon_control/assets/24434212/83b76ff8-0cde-45fb-a773-1b9f4126dfed">

Also nothing weird in the Thermostat temperatures:
<img width="795" alt="Screenshot 2023-11-15 at 09 09 44" src="https://github.com/edterbak/NodeRed_Heishamon_control/assets/24434212/2680b67d-fe8a-48ce-b4f3-cfb6ba3a2e95">

**Additional context**
- As the Softstart jumps in nicely, I got a hunch it is probably not that function.
- What happens if one of the functions somehow fails and returns null? Does it then jump back to the "basic setpoint"?
- I have problems with Heishamon and got a high MQTT reconnect rate (still need to put a ticket on that repo. While it is problematic, I do not think this problem is caused by this as the pump is set to this Tsp by mqtt (and turns on).

If it helps, here are my pump details: 
[heatpump_data.txt](https://github.com/edterbak/NodeRed_Heishamon_control/files/13361950/heatpump_data.txt)

I would love to check/look for problems myself but not sure where to start. 
Also I am a bit reluctant to update the NRF to the beta one as @edterbak mentioned they are *not so stable* yet.
Same with Heishamon (HM), as I am not sure if NRF 23.09 is fully compatible with HM 3.2.3

**Comment by edterbak** [comment]
This is a weird one. Never have I ever seen this behaviour. I will think about this more.
Also seeing the calculated WAR SP is not changing in the graph, suggests it is not the WAR function.

Can you collect the RTC corrections ?
Import this link-out node, and you can export the correction value to where you want it for that. Connect with a link-in node to [RTC Correction]

```
[
    {
        "id": "3f6602042d2dc015",
        "type": "link out",
        "z": "8c9d42231fd19d3c",
        "g": "a8ac5b148d851a6b",
        "name": "RTC Correction",
        "mode": "link",
        "links": [],
        "x": 3945,
        "y": 1460,
        "wires": []
    }
]
```

PS
You are right. v23.09 is indeed not compatible with HM 3.2.3. 
Starting from beta v23.10 beta14 it is compatible.

**Comment by edterbak** [comment]
Is there any update on this issue? 
Is it still happening?

If not, please close the issue. 
Otherwise we should continue diggin in :)
