### ISSUE TITLE
[ENHANCEMENT]: after auto DHW heat, pump is on for heating 

### ISSUE THREAD

**Issue by Bonusmp** [edterbak/NodeRed_Heishamon_control#144]
hi,

what is the reason for using a delay in turning off the pump after heating the DHW, after that for me it results in unnecessary turning on of the compressor even though the room temperature is above the target, despite sending a shutdown message, I need to check if this is a one-time action or not

<img width="572" alt="image" src="https://github.com/edterbak/NodeRed_Heishamon_control/assets/75584351/495e06b0-9fa0-4b34-8702-604b6c0231bc">

**Comment by Bonusmp** [comment]
it is no one time action 

<img width="493" alt="image" src="https://github.com/edterbak/NodeRed_Heishamon_control/assets/75584351/374ff5a8-1fe8-4349-bb89-7daf6a613faf">

**Comment by edterbak** [comment]
Hi, 
I dont fully understand your question / issue. 

The Auto-start-dhw function 
- turn on heatpump (when off)
- sets the heatpump in DHW-only modus

After it is done, and DHW setpoint is reached, the water in the pump/piping is hot. 
Forcing a operationmode switch to HEAT at this time, is not good for the floorheating piping. 50C water is too high, so the 15 minutes wait if for safety.

After 15 minutes, the operation mode is reverted to what it was befor the Auto-start-dhw

----------
So, what thing action exactly in the above text is a problem from your perspective? Please elaborate more.
Please explain what you expect, and why. 😄

**Comment by Bonusmp** [comment]
so, prebefore turning on "Auto DHW" the pump is off, next start "auto DHW", next wait 15min (now i uderstand, and it is no my problem exacly) after this time the pump turns on to heat the room even though according to the RTC function the temperature is higher from the set value (22), it did not fall below 22

from my point of view, this case, turning on the room heating is completely unnecessary, the compressor worked for 2 minutes and was turned off by the RTC function

I will change the title because this is not the error/bug/my misunderstanding

I hope I explained it more clearly now

**Comment by edterbak** [comment]
Hi. Sorry for the late reply .. 

Why is this issue closed? I think you mention a fair point.
Rtc function is to slow. I will pick this up at some point
