### ISSUE TITLE
[BUG]:V23.09: text heat,dhw,cool status missing

### ISSUE THREAD

**Issue by WP-Rue** [edterbak/NodeRed_Heishamon_control#145]
In home dashboard 2. and 3. row (and cool row if available) in the first line in the text widgets the value {{msg.payload}} is missing..
Only a simple issue, but I saw it missing on some screenshots, too.
Maybe "Label"-text was also intended..;-)

**Comment by edterbak** [comment]
Hi,
Yeah I know. I removed the status from the head of the column there. 
I moved this to the first column "Heatpump" under "Operating mode": Actual + valve position.

**Comment by WP-Rue** [comment]
> Hi,
> 
> Yeah I know. I removed the status from the head of the column there. 
> 
> I moved this to the first column "Heatpump" under "Operating mode": Actual + valve position. 
> 
> 
> 
> Simpeler solution, less code (reminds me to remove the code)

👍🏻
