### ISSUE TITLE
[ENHANCEMENT]: Softstart and Night reduction

### ISSUE THREAD

**Issue by mabek** [edterbak/NodeRed_Heishamon_control#147]
Really appreciate your effort so far, great work!
One combination I couldn't get to work properly in my case is Softstart and Night reduction.

Whenever the target temperature is lowered by night reduction and soft start lowers it even further, I am getting into situations where the heatpump shuts down very quickly.

**Describe the solution you'd like**
Option 1: Option to set a maximum correction amount :
Lets say soft start wants to do -2 and night reduction is -2 but there is a maximum correction amount of -3 the result is -3. 

Option 2: Option to have soft start only activated whenever night reduction is turned off.

**Comment by edterbak** [comment]
Hi! 😄 

Under SETTINGS, there is an option to set a hard lower limit for the setpoint.

Heat water temperature limits

Would this work for you?
There is a fixed limit where a heat pump can work well. Each situation specific ofcourse

**Comment by mabek** [comment]
I tried that option already, but according to WAR the temperatures would be to different when its cold or warmer to find a decent lower end. Did not help much.

**Comment by edterbak** [comment]
Hi, 

In the scheduler, you can already 'toggle a function'
Turn softstart off at the time night reduction is turned on and vice versa. This way you need 2 schedules to get what you want.

**Comment by mabek** [comment]
Great idea, didnt think of this one, thank you! 😄

**Comment by edterbak** [comment]
Took me a while as well :)

**Comment by edterbak** [comment]
If this is solved, you can close the issue.
