### ISSUE TITLE
[BUG]:Delay-Node missing?

### ISSUE THREAD

**Issue by WP-Rue** [edterbak/NodeRed_Heishamon_control#148]
V24.02: (and earlier) Maybe a "Delay"-Node is missing - in Chart Energy between COP calculated  and Chart "efficiency"..
I put a 1msg/2min in between, like in the other channels of the chart.

**Expected behavior**
the COP-line has then the full lenght on the chart..

Thanks for new Version 24.02!

Happy Christmas!
![image](https://github.com/edterbak/NodeRed_Heishamon_control/assets/140204844/dc26760c-eced-43b9-b808-b28bc0cd0393)

**Comment by edterbak** [comment]
Thanks for pointing this out.
Fixed in v24.03 now.

**Comment by edterbak** [comment]
![image](https://github.com/edterbak/NodeRed_Heishamon_control/assets/3155621/6e47815a-58e0-4d10-b4ad-089f278f0419)

**Comment by WP-Rue** [comment]
YES!!✅🍀

**Comment by edterbak** [comment]
Should be working fine now. 
Im closing this issue, in the assumption it is working now like it is on my end. 

If there is still an issue, you can reopen it. :)
