### ISSUE TITLE
Schedule not running when power state is off

### ISSUE THREAD

**Issue by timovd** [edterbak/NodeRed_Heishamon_control#15]
When Heatpump_State is off, the schedule is triggered, but not executed.
It would be an enhancement to have a switch (on generic level or on each line in the scheduler) to choose if the heatpump may be turned on (SET1 = 1) if TOP1 != 1.

**Comment by edterbak** [comment]
Would an option be to add an action to turn on the pump, set1,?
You can schedule turn on. An 1minute later your action.

**Comment by timovd** [comment]
I guess that would work as well, but it would give less overview.
Default Panasonic behaviour is to turn on the device, even when the device is turned off.

**Comment by edterbak** [comment]
I have added a toggle 'override' to the scheduler. 
When the pump is off, it will first turn the pump on, and 3 seconds later do the scheduled task. 
Each scheduled line can be programmed like this separatly. 

Please check if this is as you would like it. 
Suggestions are welcome
