### ISSUE TITLE
Defrost state not shown in graph

### ISSUE THREAD

**Issue by edterbak** [edterbak/NodeRed_Heishamon_control#157]
For some weird reason the defrost state (0/1) is not shown in the graph on Energy tab > Efficiency chart

**Comment by edterbak** [comment]
fixed in v24.04

**Comment by ZonPV** [comment]
![Defrost](https://github.com/user-attachments/assets/7714506c-bba6-44d9-8f86-67592ff0b40a)

Defrost is the orange line in the graph. So bug is solved in V24.04. 
Thnx @edterbak

**Comment by edterbak** [comment]
Thank you for confirming.
