### ISSUE TITLE
[BUG]: Some values of topics from Heishamon not correct for K-series

### ISSUE THREAD

**Issue by ZonPV** [edterbak/NodeRed_Heishamon_control#159]
Today I closed issue #150. That solved a problem with values of Power.
But there is still something else..

When I compare the values of my Panasonic K-series to the values of the heatpump J-series of my brother I see a few more differences.

TOP52: Defrost_Temp
TOP54: Bypass_Outlet_Temp
TOP55: Ipm_Temp
TOP90: Room_Heater_Operations_Hours
TOP91: DHW_Heater_Operations_Hours

**Expected behavior**
It will solve a problem with representing the Backup Heater hours in System, Hardware. They are 0 now.

![System Hardware](https://github.com/edterbak/NodeRed_Heishamon_control/assets/11488827/7d9e19a1-b5a6-4f35-bdcd-6a469548a2a9)

Maybe there is need for some more XTOP's in the Heishamon... But this will be the first step..

There is a list as spreadsheet with yellow marked differences.

[Verschillen J en K.xlsx](https://github.com/edterbak/NodeRed_Heishamon_control/files/13953004/Verschillen.J.en.K.xlsx)

**Comment by geduxas** [comment]
Bypass outlet is T-Cap series stuff.. regular pump's don't have bypass.
All other values should be in expected place as for older pumps.. K/L series only introduced new power topics, system pressure sensor, and additional inlet/outlet temperature sensors.

**Comment by ZonPV** [comment]
> Just now noticed your's excel, strange that's temperature apperes really are in offset.. as for model, it seam's it's not "decoded" in firmware, so it should be done in heishamon side (if not done in latest firmware) and for those temperature sensors i suggest to join heishamon slack channel, and discuss with MIG for missing temperature values.

Yes, I had the same idea, this is an issue in the firmware of Heishamon for new generation Panasonic heatpumps. 
Is this link https://gathering.tweakers.net/forum/list_messages/2102536/last to the forum you mean? 
And who or what do you mean with MIG?

I suppose that Ed will understand and pick this up.

**Comment by edterbak** [comment]
Is your pump freshly installed? Just up and running?
If so, the value 0 might just be correct for these TOPs
TOP90: Room_Heater_Operations_Hours
TOP91: DHW_Heater_Operations_Hours

I have nearly 10000 operating hours, and my values are 85 / 156 hours.

The heatpump model being shown as 255, that is information that needs to be coming from heishamon itself. 
If the heishamon is able to recognize the model and attaches a number to it which is published over MQTT (like all known models) I can translate that and show it in the dashboard. 

The -128 values. I need to know some stuff about this. If this is expected for all K-series, or an error. 
Needs some communication with the creators of heishamon for that :)

**Comment by ZonPV** [comment]
Is your pump freshly installed? Just up and running?
If so, the value 0 might just be correct for these TOPs
TOP90: Room_Heater_Operations_Hours
TOP91: DHW_Heater_Operations_Hours

My heatpump is running now about 4 weeks.
In the sheet it says TOP11  Opereration_Hours: 375 hours
So about new. 
The one of my brother: that one is in the second winter,.

My conclusion about TOP90/91: you cannot trust that counters. Or I do not understand them.. Maybe after a few months there will be progress. From 0 to 2 hours.. I will keep an eye on that.

About heatpump model: I mentioned Igor about that. He will add the "signature" of my model hp in the new firmware. So that issue is solved.
You solved the issue about XTOP0 to XTOP5 in the last version of the NR flow 24.03. Thanks for that.

About TOP52: I will have a look at that value within a few weeks, on a warmer day, in the Heishamon of my brother.

**Comment by edterbak** [comment]
Just for your information, from my manual. Maybe it helps. :) 

![image](https://github.com/edterbak/NodeRed_Heishamon_control/assets/3155621/bf2b6db0-1bc6-4717-b89d-5bcb68476fb4)

![image](https://github.com/edterbak/NodeRed_Heishamon_control/assets/3155621/823fb8a9-5368-4ec9-95b3-9f442f5deb84)

Based on this information, I THINK the backup heater is only used for short periods. Maybe this puts the low values in perspective. 
But, to conclude...  I think I do not fully understand the pumps logics for sure. It is very complex at times.

**Comment by geduxas** [comment]
@ZonPV
here is link to slack chat room, there you find meber with nickname MiG-41, he could help you find out missing sensor's

[![Join us on Slack chat room](https://img.shields.io/badge/Slack-Join%20the%20chat%20room-orange)](https://join.slack.com/t/panasonic-wemos/shared_invite/enQtODg2MDY0NjE1OTI3LTgzYjkwMzIwNTAwZTMyYzgwNDQ1Y2QxYjkwODg3NjMyN2MyM2ViMDM3Yjc3OGE3MGRiY2FkYzI4MzZiZDVkNGE)

As for data formatted in 255 or -128 they are not supported or in incorrect value. so if you get temperature topic with -128 so it means that pump is not reporting that temperature in expected location, 0 (zero) values are well expected, it could mean that your's backup heater is not used at all, you could check heater time in Panasonic screen menu also..

**Comment by edterbak** [comment]
Ok,
This means I need to filter out the -128 value befor It can be used in the node red flow.
But I think I currently do not use any of the values anywhere. Right?

Defrost_Temp
Bypass_Outlet_Temp
Ipm_Temp

**Comment by geduxas** [comment]
@edterbak don't know any use of them in flow's..
ByPass temperature related only for T-Cap model's.. it passes some refrigeration through pipe-to-pipe instead of evaporator.. 
IPM it's inverter (transistors, if remember correctly) temperature, to prevent it from overheating 
Defrost temperature, temperature on evaporator, by that it's possible predict defrost.

**Comment by ZonPV** [comment]
> Just for your information, About the top 90/91, from my manual. Maybe it helps. :)
> 
> ![image](https://private-user-images.githubusercontent.com/3155621/297525885-bf2b6db0-1bc6-4717-b89d-5bcb68476fb4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwMjA1MTUsIm5iZiI6MTcwNjAyMDIxNSwicGF0aCI6Ii8zMTU1NjIxLzI5NzUyNTg4NS1iZjJiNmRiMC0xYmM2LTQ3MTctYjg5ZC01YmNiNjg0NzZmYjQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjNUMTQzMDE1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MWUzMmI1NDc0ZTM5MjQ2NTg5YzVmMTlmYzA0NTRkZTgyY2MxM2UzMjdlODY5NTI3YWNmY2M0NjMwNjY3ZjgyMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.N0y7fHtqwWIUJbNBgDGQrcYgxCOXfqaXNCZMOeOMJPk)
> 
> ![image](https://private-user-images.githubusercontent.com/3155621/297526871-823fb8a9-5368-4ec9-95b3-9f442f5deb84.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwMjA1MTUsIm5iZiI6MTcwNjAyMDIxNSwicGF0aCI6Ii8zMTU1NjIxLzI5NzUyNjg3MS04MjNmYjhhOS01MzY4LTRlYzktOTViMy05ZjQ0MmY1ZGViODQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjNUMTQzMDE1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzdjZWM0ZTRjZDdlNGY2MThmZWI4YTg5NDJlNzdhZjNmYjM1ZGU4MWQ2ZTE3ZjExYWUzMGFiMDlkNjQ4OGU2NiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.JRWnjfyr3S1WSe7uhxn400UXMyef64DqbvWFnn_yKOw)
> 
> Based on this information, I THINK the backup heater is only used for short periods. Maybe this puts the low values in perspective. But I did not find info yet if the heater can be used in HEAT mode. If that is the case, the shown numbers do seem on the low side. :) But, to conclude... I think I do not fully understand the pumps logics for sure. It is very complex at times.


Thanks for your explanation. The name of the topic is a bit confusing to me.

I can confirm that the electric heat element can help the external heatpump more or less in heat mode. But that depends of the settings and the model. My heatpump has a 3 kW element. I think that could be the cause why TOP90 stays at 0 hours. I turned that switch of because during a test my 9 kW pump created 12 kW of heat at a moment. :-)

My conclusion: Room_Heater_Operations_Hours = Backup heater for heating the house..

That said I think that TOP91 only counts the last part of the sterilisation run.. When the backup heater is running..

**Comment by ZonPV** [comment]
> @ZonPV here is link to slack chat room, there you find meber with nickname MiG-41, he could help you find out missing sensor's
> 
> [![Join us on Slack chat room](https://camo.githubusercontent.com/cdf8ed3cc06d951d40fbaa3b3317985284de3af8443db2f68785351259079800/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f536c61636b2d4a6f696e25323074686525323063686174253230726f6f6d2d6f72616e6765)](https://join.slack.com/t/panasonic-wemos/shared_invite/enQtODg2MDY0NjE1OTI3LTgzYjkwMzIwNTAwZTMyYzgwNDQ1Y2QxYjkwODg3NjMyN2MyM2ViMDM3Yjc3OGE3MGRiY2FkYzI4MzZiZDVkNGE)
> 
> As for data formatted in 255 or -128 they are not supported or in incorrect value. so if you get temperature topic with -128 so it means that pump is not reporting that temperature in expected location, 0 (zero) values are well expected, it could mean that your's backup heater is not used at all, you could check heater time in Panasonic screen menu also..

@geduxas 
Thank you for link and additional info. I will have a look there. 
IPM temp can be good to know if you know what temperature is still oke for the pump I guess.

I checked the counters for backup heater and both values are still zero. My pump is now 1 month old so the counter for sterilisation will be almost at 1 hour with 1 run in a week and just counting the time of the backup heater.

**Comment by ZonPV** [comment]
> Ok, This means I need to filter out the -128 value befor It can be used in the node red flow. But I think I currently do not use any of the values anywhere. Right?
> 
> Defrost_Temp Bypass_Outlet_Temp Ipm_Temp

@edterbak 
No idea if you talk to me or geduxas..
I have no idea..
But I think it is nice to read those values in the NR-dashboard and know those values. I suggest that there is an indicator (or meter) if the are to high of low. :-)

**Comment by ZonPV** [comment]
After a long period with several legionella-runs it is clear that the value (TOP91) related to that function change in time. 

So I suggest to close this issue.

**Comment by ZonPV** [comment]
Thanks for the above info.
