### ISSUE TITLE
[BUG]:V24.02 !! Maybe one link from external settings interface to dashboard missing?

### ISSUE THREAD

**Issue by WP-Rue** [edterbak/NodeRed_Heishamon_control#164]
![Bildschirmfoto vom 2024-02-17 14-02-43](https://github.com/edterbak/NodeRed_Heishamon_control/assets/140204844/839dd85a-bcc2-4435-804d-8990197379ce)
I'm using still one version older V24.02. So maybe my small issue is already solved.
The link to the dashboard switch to set heat pump on/off from external signal is missing. (see screenshot: I added the link already..)

Greetings from 10°C warm germany..

**Comment by edterbak** [comment]
Hi,

Which one?
I see both "External link HEATPUMP on/off" and "External link CHANGE OPERATING MODE".
What is/was missing then?

**Comment by WP-Rue** [comment]
So-sorry. Obviously it was deleted during playing around with linking to  personal dashboard by somebody! (me)
sorry!
I close this point. Good night!
