### ISSUE TITLE
HowTo feed the values of a 3rd party grid meter to the Solar2DHW function

### ISSUE THREAD

**Issue by usauerbrey** [edterbak/NodeRed_Heishamon_control#165]
This is not a bug, but I am searching (unsucessfully) how and where I  can input the values of a 3rd party grid meter to the Solar2DHW function.
Can you help me, and pease add it to the instructions

Thanks Uwe

**Comment by geduxas** [comment]
just pin your's meeter output to flow input.. 

![image](https://github.com/edterbak/NodeRed_Heishamon_control/assets/18700450/54637ea9-5978-47d9-be0d-b79681a3b623)

**Comment by usauerbrey** [comment]
thanks, it works
Best Regards Uwe

**Comment by geduxas** [comment]
> thanks, it works Best Regards Uwe

Please close issue if it's solved
