### ISSUE TITLE
EEPROM issue

### ISSUE THREAD

**Issue by HighlyCompressedAir** [edterbak/NodeRed_Heishamon_control#169]
Using this project causes so many writes to the heat pump's EEPROM that it should break in no time. Are you aware of that?

https://github.com/Egyras/HeishaMon/issues/225

**Comment by mi-hol** [comment]
@HighlyCompressedAir how about closing this issue?

**Comment by HighlyCompressedAir** [comment]
Enabling WAR, RTC and SoftStart will cause tens of thousands of writes to a single register every year. If the EEPROM's lifetime is 100k writes which is very common, that could kill it in just a few years. I don't know why everyone just pretends like it's nothing, I don't like it. A warning on the front page is a minimum that can be done.

**Comment by geduxas** [comment]
Yes we are talking about it a lot, theoretically it's possible, how it is in reality no one knows, heishamon and this project is old enough, that should already reveal broken boards, but personally i didn't hear

**Comment by geduxas** [comment]
@mi-hol it's arguably.. now one exactly know, risk always possible.. 
Panasonic (without heishamon and taw) have additional integrations to KNX and Modbus networks.. so yes it's prepared for bigger integration into BMS system's.. also i didn't see anywhere mentioning limit of writings.. 

Also it's possible that all setting are stored in RAM, and only on power failure with help of big capacitors it writes state to flash.. i am just guessing :)

**Comment by mi-hol** [comment]
> risk always possible.

that is correct, but title says "issue". An issue is defined as: "a risk that has manifested itself"
Without evidence, this issue should be moved to "discussions"

**Comment by HighlyCompressedAir** [comment]
I wasn't aware that Panasonic supports Modbus. The fact that they do makes 100k write EEPROM highly unlikely.
