### ISSUE TITLE
[BUG]:DHW-Productions started...

### ISSUE THREAD

**Issue by WP-Rue** [edterbak/NodeRed_Heishamon_control#171]
Tonight the DHW-production startet at 1:40. Actual Tank-Temp was 46°C  with set point at 47°C. (DHW delta is 3°C)
From Logfile it seems, as this was a side effect of Quiet-Mode-Manager.
This I recognize the first time- maybe it is not worth to mention, maybe their is a small step to optimize?
Greetings rue

<img width="1234" alt="Bildschirmfoto 2024-10-01 um 07 20 59" src="https://github.com/user-attachments/assets/1cb56acb-b5e4-4075-b9ea-b9d721d602a5">
<img width="378" alt="Bildschirmfoto 2024-10-01 um 07 22 15" src="https://github.com/user-attachments/assets/4695892d-c8a7-43e9-ab70-c8c06f6e780a">
<img width="1149" alt="Bildschirmfoto 2024-10-01 um 07 24 11" src="https://github.com/user-attachments/assets/0fda4156-6f16-45e8-be9c-5f3caae5e90a">
<img width="770" alt="Bildschirmfoto 2024-10-01 um 07 24 48" src="https://github.com/user-attachments/assets/f1b62a54-232e-4128-96d3-66f02c78b0dc">
<img width="1322" alt="Bildschirmfoto 2024-10-01 um 09 57 59" src="https://github.com/user-attachments/assets/02972884-e176-4cbf-ab5e-383e35057a7c">

**Comment by edterbak** [comment]
Hi,

What do you think the issue is?
In the log I see no indication that the DHW cycle is started by the node red flow. 
01:40:31 - Three way valvue switches to positoin DHW
then
01:40:31 - then the softstart function is reacting by restoring quiet mode

IF it was the other way around, you would first see a SET command in the log and xx seconds later the confirmation of the three-way-valvue has switched position

Or am I not understanding the issue you are trying to tell me?

**Comment by WP-Rue** [comment]
Hi Ed,
maybe this is no issue.
The point is- I don't understand, why the pump is starting- and I hoped, their is an explanation somewhere...
My understanding is, that somehow the pump decided to switch the valve from room (because their was heating of the house, which I switched off probably manually at 21:39 the day before: 09 21:39:05 - MQTT Command: SetOperationMode: 3) to DHW.
Is their a possibility that the flow reacts in switching on the pump- maybe from quietmode manager?
Sorry for questions- I cannot analyse your flow in depth..

Probably this is no issue of the flow but a reaction from the pump itself- which I nevertheless not understand: the set point is only 1C higher than tank temperature. So who and why starts the compressor...?
Greetings 
Rue

**Comment by WP-Rue** [comment]
Maybe it is not an important topic- so I will close it in the next days.
