### ISSUE TITLE
settings - DHW/HEAT. show current value 

### ISSUE THREAD

**Issue by edterbak** [edterbak/NodeRed_Heishamon_control#19]
Some settings in the tab Settings - DHW/HEAT, are available as TOPxx mqtt topic to read the actual value from the HP. 
These values need to be visualized in the GUI.

![image](https://user-images.githubusercontent.com/3155621/155901843-4ccb7443-152a-40fc-8ba9-14bdab0221c2.png)

**Comment by lampy2** [comment]
As discussed on Tweakers, I expect the TOP values of the items in 2 are:
<html><body>


TOP22 | main/DHW_Heat_Delta | DHW heating delta (-12 to -2) (K)
-- | -- | --
TOP23 | main/Heat_Delta | Heat delta (K)
TOP24 | main/Cool_Delta | Cool delta (K)


</body>
</html>

**Comment by edterbak** [comment]
I have added all of the above SET/TOP topics so it is represented in Dashboard correctly.
Also I have added other SET/TOP topics which are NOT visible (yet) in the dashboard, but now available as global variable.
