### ISSUE TITLE
Request feature (Compressor runtime)

### ISSUE THREAD

**Issue by boutermw** [edterbak/NodeRed_Heishamon_control#28]
For the HOME dashboard it would be nice to add a indicator to show how long the compressor is running since last start.
And I don't know the function of FAN2, but if it isn't used then please remove it.

example:
![2022-05-29 (8)](https://user-images.githubusercontent.com/15846145/170874520-2ecd8a50-ef4c-4b27-b580-f4790cb7ce1f.png)

**Comment by edterbak** [comment]
I need to figure out notifications in github. 
I will pick this up soon

**Comment by edterbak** [comment]
Both items in your request are now implemented in v15. come and get it.

**Comment by boutermw** [comment]
Thanks, will check it out!
