### ISSUE TITLE
[BUG]:wrong maximum en minimum watts display on "power live meter"

### ISSUE THREAD

**Issue by sjampeter** [edterbak/NodeRed_Heishamon_control#41]
the power live meter will show the max and min watts ever recorded

when adjusting the P1 power meter to the right values in the correction function node, (factor 1000) , the power live meter uses the wrong values.
the problem occures when you begin with the wrong factor and can't be changed or resetted after.
there has to be a way to reset the min and max values of the power live meter
![image](https://user-images.githubusercontent.com/111011786/183995828-6f7b5831-37d4-41b8-a85d-53ca184cefef.png)
the actual watts in the picture above should be 13784 watts instead of 13784000 watts (would be nice though)

**Comment by edterbak** [comment]
Fixed this in next release. with a button [RESET SCALE] underneath power live chart.

**Comment by sjampeter** [comment]
Great!!!

**Comment by edterbak** [comment]
Now in beta 19.1

**Comment by edterbak** [comment]
@sjampeter  can you check if it is now as you wanted it?

**Comment by sjampeter** [comment]
just uploaded V19.2. works like a charme. thumbs up

**Comment by edterbak** [comment]
Thanks! ill close this one
