### ISSUE TITLE
[BUG]: T outlet (SP) jumps to 20°C and stop the WP

### ISSUE THREAD

**Issue by hoeckelp** [edterbak/NodeRed_Heishamon_control#55]
Hello, 
T outlet (SP) is 29°C, the WP starts. after 2-5 Minutes the T outlet (SP) jumps for a short moment to 20°C an the Maschine stops. A Moment later the T outlet (SP) jumps to 29°C back, the WP starts again. 
It is possible to log, why the T outlet (SP) is changend?

**Comment by edterbak** [comment]
HI, and welcome.
What version are you using? The beta or the version from main page?
IF you are using the latest beta, you should have a lot more logging pressent :) 

Are you using HomeAssistant integration as well? If so, make sure you have disabled all automation rules. 
Two captains on one ship wont work well.

**Comment by hoeckelp** [comment]
Hello,
i used so main version, now i have installed the beta one. You can close this bugreport, i will test the new version

**Comment by edterbak** [comment]
There will be an update soon, there is a slight issue with the SoftStart function. It is too powerfull in response if you enable it. 
so that is the only item to keep in mind. :) 

good luck
