### ISSUE TITLE
2 Errors in "T_outside - Input selector" WP Control

### ISSUE THREAD

**Issue by MarcDerSeemann** [edterbak/NodeRed_Heishamon_control#60]
First og all I want to say a big thank you for all the work and efforts for this flows as I personally would be never able to do this work.

And as I´m new to Heishamon and Node Red I hope the error does not sit in front of the computer.

The "T_outside - Input selector" function gives me two errors:
1: "TimeElapsed" is wavey underlined and the following error message: "Cannot find name 'TimeElapsed'.(2304)"
2. The first "msg3" is wavey underlined with following error message: "Property 'topic' is missing in type '{ payload: any; }' but required in type '{ topic: string; }'.(2741)
86(102, 17): 'topic' is declared here."

In the dashboard the outside temeperature remains empty.

**Comment by edterbak** [comment]
HI Marc,

Sorry for the late reply. I just noticed the now items in the issue list. 

What version of the flow are you using? Main, beta or beta 2.

**Comment by MarcDerSeemann** [comment]
Hi,

no worries about the late reply. 
I installed the fows last month it has the "softstart" function already and therefore I think it is the latest version.

**Comment by edterbak** [comment]
That still does not say much. it is in all versions :)

But I am going to rework the logic in this part soon anyway. It should be tackled soon.
Make sure you check the changelog on the beta's

**Comment by MarcDerSeemann** [comment]
Hi,

sorry, I didn´t understood the question. Of course you meant the Node Red version, now I got it.
I´m using 3.0.2, it should be the main/stable version.

**Comment by edterbak** [comment]
Are you still having these errors?
I cant reproduce them.
