### ISSUE TITLE
Send values to influxdb

### ISSUE THREAD

**Issue by ZonPV** [edterbak/NodeRed_Heishamon_control#61]
Would be nice when values of extra sensors like 1Wire or S0-meters or the HP can be send to visualise later on in Grafana.

Which sensors could be managed in Node-Red or in the dashboard.

**Comment by edterbak** [comment]
you can import this: it will allow all heishamon values to be transported to influx

`
[
    {
        "id": "8981326232694a8d",
        "type": "group",
        "z": "3dca1ce4590fa366",
        "style": {
            "stroke": "#999999",
            "stroke-opacity": "1",
            "fill": "none",
            "fill-opacity": "1",
            "label": true,
            "label-position": "nw",
            "color": "#a4a4a4"
        },
        "nodes": [
            "aaae14a2ff82a71e",
            "3f9d5719b8a33a92",
            "320a97991eb70927",
            "769d7e214d94c4aa",
            "4508dcd14eb2ee5c",
            "cd0e696b1658d440",
            "d13199f0fe111efd"
        ],
        "x": 74,
        "y": 159,
        "w": 992,
        "h": 162
    },
    {
        "id": "aaae14a2ff82a71e",
        "type": "mqtt in",
        "z": "3dca1ce4590fa366",
        "g": "8981326232694a8d",
        "name": "Heishamon",
        "topic": "panasonic_heat_pump/main/#",
        "qos": "0",
        "datatype": "auto",
        "broker": "92e5b2c.00a8b5",
        "nl": false,
        "rap": false,
        "inputs": 0,
        "x": 230,
        "y": 280,
        "wires": [
            [
                "3f9d5719b8a33a92"
            ]
        ]
    },
    {
        "id": "3f9d5719b8a33a92",
        "type": "function",
        "z": "3dca1ce4590fa366",
        "g": "8981326232694a8d",
        "name": "Map sensor to ID",
        "func": "// if there's an entry in the global defined variable then \n// the value needs to be saved (send) to next function \nvar sensorsplit = msg.topic.split(\"/\");\nvar sensor = sensorsplit[sensorsplit.length-1];\n \nvar sensorvalue = msg.payload;\nfor (i = 0; i < context.global.heishamon.SensorMapping.length; i++) {\n    // when sensor is in the global settings \n    msg.sensor = sensor;\n    if(sensor == context.global.heishamon.SensorMapping[i][0]){\n\n        return msg;\n    }\n}\nreturn;",
        "outputs": 1,
        "noerr": 0,
        "initialize": "",
        "finalize": "",
        "libs": [],
        "x": 490,
        "y": 280,
        "wires": [
            [
                "4508dcd14eb2ee5c"
            ]
        ]
    },
    {
        "id": "320a97991eb70927",
        "type": "function",
        "z": "3dca1ce4590fa366",
        "g": "8981326232694a8d",
        "name": "global setup",
        "func": "if (!context.global.heishamon) {\n  context.global.heishamon = {};\n}\n\ncontext.global.heishamon.HAapplication = \"InfluxDB\";\n\n//This is the overview of sensors which has to be sent to the Home Automation system\ncontext.global.heishamon.SensorMapping = [\n        //  [\"name of topic\"]\n            [\"Heatpump_State\"],\n            [\"Pump_Flow\"],\n            [\"Force_DHW_State\"], //DHW status (20=off, 10=on 0=unknown)\n            [\"Quiet_Mode_Schedule\"],\n            [\"Operating_Mode_State\"], //7 levels - (0=Heat only, 10=Cool only, 20=Auto, 30=DHW only, 40=Heat+DHW, 50=Cool+DHW, 60=Auto+DHW)\n            [\"Main_Inlet_Temp\"],\n            [\"Main_Outlet_Temp\"], \n            [\"Main_Target_Temp\"],\n            [\"Compressor_Freq\"],\n            [\"DHW_Target_Temp\"],\n            [\"DHW_Temp\"],\n            [\"Operations_Hours\"],\n            [\"Operations_Counter\"],\n            [\"Main_Schedule_State\"],\n            [\"Outside_Temp\"],\n            [\"Heat_Energy_Production\"],\n            [\"Heat_Energy_Consumption\"],\n            [\"Powerful_Mode_Time\"], //  4 levels -- 0= off - 10= 30 Minute - 20= 60 Minute - 30= 90 Minute //0= off, 30 = level 3\n            [\"Quiet_Mode_Level\"], // 4 levels -- 0= off - 10= Silent 1 - 20= Silent 2 - 30= Silent 3\n            [\"Holiday_Mode_State\"],\n            [\"ThreeWay_Valve_State\"], // 2 levels -- 0=Room, 10=DHW\n            [\"Outside_Pipe_Temp\"],\n            [\"DHW_Heat_Delta\"],\n            [\"Heat_Delta\"],\n            [\"Cool_Delta\"],\n            [\"DHW_Holiday_Shift_Temp\"],\n            [\"Defrosting_State\"],\n            [\"Z1_Heat_Request_Temp\"],\n            [\"Z1_Cool_Request_Temp\"],\n            [\"Z1_Heat_Curve_Target_High_Temp\"],\n            [\"Z1_Heat_Curve_Target_Low_Temp\"],\n            [\"Z1_Heat_Curve_Outside_High_Temp\"],\n            [\"Z1_Heat_Curve_Outside_Low_Temp\"],\n            [\"Room_Thermostat_Temp\"],\n            [\"Z2_Heat_Request_Temp\"],\n            [\"Z2_Cool_Request_Temp\"],\n            [\"Z1_Water_Temp\"],\n            [\"Z2_Water_Temp\"],\n            [\"Cool_Energy_Production\"],\n            [\"Cool_Energy_Consumption\"],\n            [\"DHW_Energy_Production\"],\n            [\"DHW_Energy_Consumption\"],\n            [\"Z1_Water_Target_Temp\"],\n            [\"Z2_Water_Target_Temp\"],\n            [\"Error\"],\n            [\"Room_Holiday_Shift_Temp\"],\n            [\"Buffer_Temp\"],\n            [\"Solar_Temp\"],\n            [\"Pool_Temp\"],\n            [\"Main_Hex_Outlet_Temp\"],\n            [\"Discharge_Temp\"],\n            [\"Inside_Pipe_Temp\"],\n            [\"Defrost_Temp\"],\n            [\"Eva_Outlet_Temp\"],\n            [\"Bypass_Outlet_Temp\"],\n            [\"Ipm_Temp\"],\n            [\"Z1_Temp\"],\n            [\"Z2_Temp\"],\n            [\"DHW_Heater_State\"],\n            [\"Room_Heater_State\"],\n            [\"Internal_Heater_State\"],\n            [\"External_Heater_State\"],\n            [\"Fan1_Motor_Speed\"],\n            [\"Fan2_Motor_Speed\"],\n            [\"High_Pressure\"],\n            [\"Pump_Speed\"],\n            [\"Low_Pressure\"],\n            [\"Compressor_Current\"],\n            [\"Force_Heater_State\"],\n            [\"Sterilization_State\"],\n            [\"Sterilization_Temp\"],\n            [\"Sterilization_Max_Time\"],\n            [\"Z1_Cool_Curve_Target_High_Temp\"],\n            [\"Z1_Cool_Curve_Target_Low_Temp\"],\n            [\"Z1_Cool_Curve_Outside_High_Temp\"],\n            [\"Z1_Cool_Curve_Outside_Low_Temp\"],\n            [\"Heating_Mode\"],\n            [\"Heating_Off_Outdoor_Temp\"],\n            [\"Heater_On_Outdoor_Temp\"],\n            [\"Heat_To_Cool_Temp\"],\n            [\"Cool_To_Heat_Temp\"],\n            [\"Cooling_Mode\"],\n            [\"Heat_To_Cool_Temp\"],\n            //[\"Z2_Heat_Curve_Target_High_Temp\"],\n            //[\"Z2_Heat_Curve_Target_Low_Temp\"],\n            //[\"Z2_Heat_Curve_Outside_High_Temp\"],\n            //[\"Z2_Heat_Curve_Outside_Low_Temp\"],\n            //[\"Z2_Cool_Curve_Target_High_Temp\"],\n            //[\"Z2_Cool_Curve_Target_Low_Temp\"],\n            //[\"Z2_Cool_Curve_Outside_High_Temp\"],\n            //[\"Z2_Cool_Curve_Outside_Low_Temp\"],\n            [\"Room_Heater_Operations_Hours\"],\n            [\"DHW_Heater_Operations_Hours\"]\n    ];\n    \ncontext.global.heishamon.ActionMapping = [\n    // actioncommand\n    [\"SetHeatpump\"],\n    [\"SetHoliday\"],\n    [\"SetQuietMode\"],\n    [\"SetPowerfull\"],\n    [\"SetZ1HeatRequestTemperature\"],\n    [\"SetZ1CoolRequestTemperature\"],\n    [\"SetZ2HeatRequestTemperature\"],\n    [\"SetZ2CoolRequestTemperature\"],\n    [\"SetOperationMode\"],\n    [\"SetForceDHW\"],\n    [\"SetDHWTemp\"],\n    [\"SetCoolTemp\"],\n    [\"SetForceDefrost\"],\n    [\"SetForceSterilization\"]\n];\nreturn msg;",
        "outputs": 1,
        "noerr": 0,
        "initialize": "",
        "finalize": "",
        "libs": [],
        "x": 470,
        "y": 240,
        "wires": [
            []
        ]
    },
    {
        "id": "769d7e214d94c4aa",
        "type": "inject",
        "z": "3dca1ce4590fa366",
        "g": "8981326232694a8d",
        "name": "",
        "props": [
            {
                "p": "payload"
            },
            {
                "p": "topic",
                "vt": "str"
            }
        ],
        "repeat": "",
        "crontab": "",
        "once": true,
        "onceDelay": 0.1,
        "topic": "Startup",
        "payload": "",
        "payloadType": "date",
        "x": 260,
        "y": 240,
        "wires": [
            [
                "320a97991eb70927"
            ]
        ]
    },
    {
        "id": "4508dcd14eb2ee5c",
        "type": "function",
        "z": "3dca1ce4590fa366",
        "g": "8981326232694a8d",
        "name": "Prepare InfluxDB output",
        "func": "if(isNaN(parseFloat(msg.payload))){\n    return;\n}else{\n    \n    msg.payload = [{\n        numValue: parseFloat(msg.payload),\n        strValue: msg.sensor\n    },\n    {\n        topic:msg.sensor\n    }];\n    return msg;\n}",
        "outputs": 1,
        "noerr": 0,
        "initialize": "",
        "finalize": "",
        "libs": [],
        "x": 710,
        "y": 280,
        "wires": [
            [
                "d13199f0fe111efd"
            ]
        ]
    },
    {
        "id": "cd0e696b1658d440",
        "type": "comment",
        "z": "3dca1ce4590fa366",
        "g": "8981326232694a8d",
        "name": "Send Heishamon to INFLUXdb",
        "info": "",
        "x": 230,
        "y": 200,
        "wires": []
    },
    {
        "id": "d13199f0fe111efd",
        "type": "influxdb out",
        "z": "3dca1ce4590fa366",
        "g": "8981326232694a8d",
        "influxdb": "c38793a96c45b9e5",
        "name": "Panasonic heatpump",
        "measurement": "heishamon",
        "precision": "",
        "retentionPolicy": "",
        "database": "Panasonic",
        "precisionV18FluxV20": "s",
        "retentionPolicyV18Flux": "",
        "org": "Home",
        "bucket": "Panasonic heatpump",
        "x": 940,
        "y": 280,
        "wires": []
    },
    {
        "id": "92e5b2c.00a8b5",
        "type": "mqtt-broker",
        "name": "MQTT (x.x.x.x)",
        "broker": "x.x.x.x",
        "port": "1883",
        "clientid": "Node_Red_Client",
        "autoConnect": true,
        "usetls": false,
        "compatmode": false,
        "protocolVersion": "4",
        "keepalive": "60",
        "cleansession": true,
        "birthTopic": "",
        "birthQos": "0",
        "birthRetain": "false",
        "birthPayload": "",
        "birthMsg": {},
        "closeTopic": "",
        "closeQos": "0",
        "closeRetain": "false",
        "closePayload": "",
        "closeMsg": {},
        "willTopic": "",
        "willQos": "0",
        "willRetain": "false",
        "willPayload": "",
        "willMsg": {},
        "sessionExpiry": ""
    },
    {
        "id": "c38793a96c45b9e5",
        "type": "influxdb",
        "hostname": "localhost",
        "port": "8086",
        "protocol": "https",
        "database": "test",
        "name": "InfluxDB",
        "usetls": true,
        "tls": "",
        "influxdbVersion": "2.0",
        "url": "http://x.x.x.x:8086",
        "rejectUnauthorized": false
    }
]
`

**Comment by edterbak** [comment]
if you change in the mqtt input the main/# to s0/#, you can select the source from the heishamon.

Everything that is available in mqtt, is available to push to influx

**Comment by edterbak** [comment]
Better to get the latest version from here
https://github.com/edterbak/NodeRed_Heishamon_control/tree/main-22-beta_2/heishamon2influxdb

**Comment by edterbak** [comment]
This is not directly linked to the main project. Side dish, not in any Milestone

**Comment by edterbak** [comment]
Keep this card here as a reminder until v22.00 stable has been released and confirmed that this flow is also available on the main page.
