### ISSUE TITLE
on off switches in schedules not inline

### ISSUE THREAD

**Issue by balans911** [edterbak/NodeRed_Heishamon_control#7]
the first rules and on on/off switches are not inline

**Comment by edterbak** [comment]
Fixed in release v8

**Comment by edterbak** [comment]
Kindly verify if the bug is really solved. If so, I will close this issue

**Comment by edterbak** [comment]
To give a little background on this issue.
I have created the dashboard with blank speces here and there. It looks great in my dash. But as it turns out, while importing those blank spaces are auto-filled (shuffled).

**Comment by balans911** [comment]
fixed !
