### ISSUE TITLE
[BUG]: On Temperature page the Ta is plotted on the living room graph.

### ISSUE THREAD

**Issue by blb4github** [edterbak/NodeRed_Heishamon_control#75]
**Describe the bug**
On Temperature page the Ta is plotted on the living room graph. I believe it should be Living room setpoint and living room actual temperature. Due to the fact Ta is plotted (temperature > 30 degrees in my case) the minimum temp on the graph is 20 degrees which means the Living room temperature is not on the graph (as it is below 20).

**To Reproduce**
Open the Temperature page

**Expected behavior**
I believe it should be Living room setpoint and living room actual temperature. Due to the fact Ta is plotted (temperature > 30 degrees in my case) the minimum temp on the graph is 20 degrees which means the Living room temperature is not on the graph (as it is below 20).

**Screenshots**

<img width="498" alt="Scherm­afbeelding 2023-01-19 om 14 29 46" src="https://user-images.githubusercontent.com/35904565/213455576-fefd945b-9a29-4e19-b737-89c03970f278.png">

**Comment by edterbak** [comment]
True. putting it on my name is fine.

**Comment by edterbak** [comment]
Fixed in 22.12

**Comment by blb4github** [comment]
Thanks, I confirm this is fixed!
