### ISSUE TITLE
[ENHANCEMENT]: Improvement Softstart function to get Compressor frequency further down if not yet on lowest level and SS correction is positive

### ISSUE THREAD

**Issue by blb4github** [edterbak/NodeRed_Heishamon_control#79]
**Is your feature request related to a problem or use case? Please describe.**
I'm a big fan of the soft start function, this function is key to have the HP running at low pace. But I believe it can be improved a bit as I see sometimes the HP running at a pace far above the minimum 19/20Hz but also with a positive SS correction.

**Describe the solution you'd like**
If the HP is running on a relative high pace (e.g. 30 Hz),the SS correction is positive (+1 or more) and the Ta is less than 1 degree above setpoint the SS correction should be decreased with 1.

**Describe alternatives you've considered**
I do have max SS correction at +5, maybe the behavour would be better if I limit to +3 but in that case there will be situations the run will stop sooner than I like.

**Additional context**
software v21.47, restart after defrost enabled
<img width="1419" alt="Scherm­afbeelding 2023-01-19 om 15 44 21" src="https://user-images.githubusercontent.com/35904565/213473259-f042d615-a25f-404d-b6d9-c18877a66ba4.png">
I updated the picture to show the decrease of setpoint over time after my intervention.

**Comment by edterbak** [comment]
Hoi,

Do we think the current implementation in v22.08+ is good enough to not need this ?

**Comment by blb4github** [comment]
With the new versions (current v22.16) the SoftStart function performs very well and this issue is solved, thanks!!

**Comment by edterbak** [comment]
Thank you for the feedback
