### ISSUE TITLE
WAR default max temp 

### ISSUE THREAD

**Issue by balans911** [edterbak/NodeRed_Heishamon_control#8]
in WAR the default temperature is a max of 40 C, perhaps for non floor heaters add the option to max 55 in the WP dash like in the standard panasonic remote

**Comment by edterbak** [comment]
@balans911 
In the GUI (Settings) I have added settings for Upper limit and Lower limit. 
They will be used in the function.
If they are not given (defined), they will not be used in the function.
Should be present and working in v8.

Please verify that this is what you are looking for and give feedback. :)

**Comment by balans911** [comment]
Nice add but not what i ment sorry, in the WP Dash , in the Function (WAR) settings box i mod the war_ot1,2,3 and the war_wt1,2,3 topic from  max 40 to max 55 like in the panasonic remote.

**Comment by edterbak** [comment]
Ah, ok 
So there currently is a limit of 40deg, which you want to increase to 50. Correct?

**Comment by balans911** [comment]
yes! fixed thnx and now enjoy your week of holiday
