### ISSUE TITLE
[BUG]: 2 softstart corrections in 1 second

### ISSUE THREAD

**Issue by fietsensloper** [edterbak/NodeRed_Heishamon_control#80]
I'm having a lot of softstart corrections. Sometimes even 2 in 1 second.

19/01 11:39:13 - Function SoftStart: Correction: 2 > 1 °C - (STABLE) Freq: 21Hz, SP_Final: 31°C
19/01 11:38:59 - Function SoftStart: Correction: 1 > 2 °C - (STABLE) Freq: 21Hz, SP_Final: 32°C
19/01 11:38:59 - MQTT Command: SetZ1HeatRequestTemperature: 31 (SoftStart)
19/01 11:38:59 - Function SoftStart: Correction: 2 > 1 °C - (STABLE) Freq: 21Hz, SP_Final: 31°C

But mostly they are like this:

19/01 10:48:59 - MQTT Command: SetZ1HeatRequestTemperature: 31 (SoftStart)
19/01 10:48:59 - Function SoftStart: Correction: -1 > 0 °C - (STABLE) Freq: 34Hz, SP_Final: 31°C
19/01 10:48:43 - MQTT Command: SetZ1HeatRequestTemperature: 30 (SoftStart)
19/01 10:48:43 - Function SoftStart: Correction: 0 > -1 °C - (CATCH) Freq: 35Hz, SP_Final: 30°C
19/01 10:48:13 - MQTT Command: SetZ1HeatRequestTemperature: 31 (SoftStart)
19/01 10:47:59 - Function SoftStart: Correction: -1 > 0 °C - (CATCH) Freq: 37Hz, SP_Final: 31°C
19/01 10:47:59 - MQTT Command: SetZ1HeatRequestTemperature: 30 (SoftStart)
19/01 10:47:59 - Function SoftStart: Correction: 0 > -1 °C - (CATCH) Freq: 37Hz, SP_Final: 30°C

Log only says Softstart, so there's no influence from RTC or WAR. 

I was running V21.29 for a few weeks, and since this morning V21.47. I had the problem in both versions. 
I'm running Node-red in Home Assistant. Manually turned off all the automations so i'm sure it's not coming from HA. 
Heishamon firmware 3.0. 
How often new values are collected from heatpump: 15 seconds
How often all heatpump values are retransmitted to MQTT broker: 20 seconds

Here's another one from 20 minutes ago:(V21.47)
19/01 17:10:30 - MQTT Command: SetZ1HeatRequestTemperature: 32 (SoftStart)
19/01 17:09:45 - Function SoftStart: Correction: 2 > 3 °C - (STABLE) Freq: 35Hz, SP_Final: 32°C
19/01 17:09:45 - MQTT Command: SetZ1HeatRequestTemperature: 31 (SoftStart)
19/01 17:09:45 - Function SoftStart: Correction: 3 > 2 °C - (STABLE) Freq: 35Hz, SP_Final: 31°C
19/01 17:09:30 - Function SoftStart: Correction: 2 > 3 °C - (STABLE) Freq: 35Hz, SP_Final: 32°C
19/01 17:08:45 - Function SoftStart: Correction: 3 > 2 °C - (STABLE) Freq: 34Hz, SP_Final: 31°C
19/01 17:08:45 - MQTT Command: SetZ1HeatRequestTemperature: 32 (SoftStart)
19/01 17:08:45 - Function SoftStart: Correction: 2 > 3 °C - (STABLE) Freq: 34Hz, SP_Final: 32°C
19/01 16:51:00 - MQTT Command: SetZ1HeatRequestTemperature: 31 (SoftStart)

**Comment by edterbak** [comment]
As stated in the tweakers forum, i found the cause. Wil fix soon

**Comment by edterbak** [comment]
Is this issue still present?

**Comment by edterbak** [comment]
Considdering this fixed.
