### ISSUE TITLE
[BUG]: Default value for HEAT_SP_upper_limit not set  at first start.

### ISSUE THREAD

**Issue by Maarten69** [edterbak/NodeRed_Heishamon_control#81]
**Describe the bug**
Default value for HEAT_SP_upper_limit not set  at first start.

**To Reproduce**
Delete the global var in context data and find out that this value will not be set.

**Expected behavior**
A default value must be set (100?)

**Version**
V21.48 beta and earlier.

**Comment by edterbak** [comment]
fixed
