### ISSUE TITLE
[BUG]: QM settings via scheduler do have impact on QM level in SS function which should be configurable seperately.

### ISSUE THREAD

**Issue by blb4github** [edterbak/NodeRed_Heishamon_control#91]
**Describe the bug**
If you set QM level via scheduler the new value is also copied to Setting page QM level. This means enabling Quietmode for the SS function doesn't do anything anymore. 

**To Reproduce**
1. Schedule a QM level on the scheduler page
2. enable Quietmode on the SS page
3. check after the timer expire the log (QM level set and send) and the QM level at the settings page
4. check with the next run Quietmode is not set as the level used by the SS function is the same as the current level.

**Expected behavior**
It should be possible to set the QM level for the SS function separate from the default QM level on the settings page;
It should be possible to set the default and the SS function QM level via the scheduler

**Screenshots**

**Comment by MikeyMan83** [comment]
Isn't it easier to have SoftStart always use QM3, independent of any other setting?

**Comment by blb4github** [comment]
Wint version v22.09 the QM function is now working very cleary.

**Comment by edterbak** [comment]
Thanks :)
