### ISSUE TITLE
[ENHANCEMENT]: Add Cool functionality to dashboard

### ISSUE THREAD

**Issue by MikeyMan83** [edterbak/NodeRed_Heishamon_control#92]
Still cold, but some time it will be summer. 

The cool functionality is absent at the moment. Should be a lot simpler than the heating function, as there is limited room for the temperature. Just needs to be above condensation point.

Would be nice to add this functionality to the COP and Energy calculations as well.

**Comment by edterbak** [comment]
<img src= "https://github.com/edterbak/NodeRed_Heishamon_control/blob/main/images/Schermafbeelding%202023-01-25%20220116.png?raw=true" width="1000">

**Comment by MikeyMan83** [comment]
Euh, yeah, I meant the landing page. Currently only on/off it seems?

**Comment by MikeyMan83** [comment]
Room temperature is empty over here... Thought it isn't working at all yet. Might be an idea to add some on/off or RTC automation?

**Comment by edterbak** [comment]
it requires a good temperature + humidity sensor.

**Comment by edterbak** [comment]
> Room temperature is empty over here... Thought it isn't working at all yet. Might be an idea to add some on/off or RTC automation?

noooooo.... aaargh... keep it simpel at first so it works.. step 1.
then we will see further.

**Comment by MikeyMan83** [comment]
> it requires a good temperature + humidity sensor. needs to be improved only

A different temperature sensor then the one I already have in my thermostat? 

Don't think humidity sensor should be a prerequisite to turn it even on or off.

**Comment by edterbak** [comment]
the humidity sensor is required to prevent the cooled area, radiator or floorheating/cooling, to be to low. under the dewpoint temp. If you cool too low, water condensates on the radiator or on your floor. 

You can ofcourse run it without, but you run a risk of a wet floor/radiator. 

In the logic I have built in that screenshot, the SP temperature is kept 2c above the dewpoint.

**Comment by edterbak** [comment]
But it is to be improved. GUI wise, and functionality wise.

**Comment by MikeyMan83** [comment]
Just had a look at the flow. 
The temperature is a separate link. So i linked that to the room temperature sensor. 

Humidity now comes from buienradar, but it shows at least it's working.

I'll check and see which humidity sensor to start using.


![image](https://user-images.githubusercontent.com/6270724/214791960-98dccd5d-1112-4f33-af29-4d3f572bdd23.png)

**Comment by edterbak** [comment]
> Just had a look at the flow. The temperature is a separate link. So i linked that to the room temperature sensor.
> 
> Humidity now comes from buienradar, but it shows at least it's working. Could have checked that sooner of course :P
> 
> I'll check and see which humidity sensor to start using.
> 
> ![image](https://user-images.githubusercontent.com/6270724/214791960-98dccd5d-1112-4f33-af29-4d3f572bdd23.png)

Maybe stating the obvious.... But using buienradar (online info) will not work. It needs to be the humidity from inside the house. Otherwise it is fairly useless. At the minimum, waaaay to optimistic.

**Comment by MikeyMan83** [comment]
Of course... But had to check if I could get it working at least.

Now I'll have to start looking for a humidity sensor.

**Comment by edterbak** [comment]
MikeyMan, Is this card / issue solved? can I close it? or is there still somthing to do for me on this?

**Comment by edterbak** [comment]
I'll close this issue then. Thanks. 
If something needs to be done again about this. we can just create a new issue/request for that.
