### ISSUE TITLE
[BUG]: Fix room temperature readout during NR Deploy

### ISSUE THREAD

**Issue by MikeyMan83** [edterbak/NodeRed_Heishamon_control#93]
When using an external temperature sensor, the flow will fall back on the PAnasonic internal heater measurement.
This impacts RTC quite badly.

Example of lots of deploys:

![image](https://user-images.githubusercontent.com/6270724/214670001-0c710a53-0f1b-4f53-9387-d8c1c437bda0.png)

**Comment by edterbak** [comment]
this is already on the board to be fixed.

**Comment by edterbak** [comment]
Fixed in v22.11
