### ISSUE TITLE
[ENHANCEMENT]: Secondary ‘emergency’ setpoint for DHW

### ISSUE THREAD

**Issue by MikeyMan83** [edterbak/NodeRed_Heishamon_control#95]
Scenario; 

ADD a second setpoint for DHW. This could function as a fallback for cold water.
Example: current setting 48 degrees with 6 degrees delta.
Secondary setpoint at 35 (setting in UI) degrees as a trigger for a forced DHW run. 

This eliminates the risk for cold water.

**Comment by MikeyMan83** [comment]
While we're at it, maybe also add a 'force dhw run now' button somewhere on the home screen. Maybe with a link in node.

**Comment by BazemanKM** [comment]
How is Works in Domoticz, to heat extra for bath

if Vakantie.active and Bad.active then
Bad.switchOff()
        
elseif Bad.active and SensorZonneboiler.temperature > 63 then (could be the Do not force if DHW is above setting in schedule)
Bad.switchOff()

elseif Bad.active and not Vakantie.active and not Badwater.active then
SetWarmwater.updateSetPoint(63)
Badwater.switchOn()
Force DHW On
Save original settings
	        
 elseif Bad.active and not Vakantie.active and (SensorBoven > '63' )
Badwater.switchOff()
Bad.switchOff()
Force DHW OFF and back to original setpoints

**Comment by edterbak** [comment]
I am working on it now. Rough implementation

**Comment by edterbak** [comment]
![image](https://github.com/edterbak/NodeRed_Heishamon_control/assets/3155621/8e93d55a-3d64-4497-9230-fa5cfda384c4)

**Comment by BazemanKM** [comment]
Normal setpoint is e.g. 52, for extra heat bath a setpoint of e.g. 63 is needed. want one button to activate mode.

**Comment by edterbak** [comment]
@BazemanKM Ah, I get your request now. It is not the same as MikeyMan put in this issue. 

I need to think about your request on how to implement that in a general way.

**Comment by edterbak** [comment]
@BazemanKM 
What I can do is create a small flow which includes a button. 
If you press the button, the DHW sp2 is set, operating mode is changed to what you desire. 
You could import this in a personal tab/flow inside node red. (not talking about GUI). 

Is this suitable for you?

**Comment by edterbak** [comment]
I currently built this

![image](https://github.com/edterbak/NodeRed_Heishamon_control/assets/3155621/ae9dc62d-c86f-47a9-99c4-270f1c52a687)

**Comment by edterbak** [comment]
![image](https://github.com/edterbak/NodeRed_Heishamon_control/assets/3155621/f8f11db0-c699-4908-b8f7-b46ae1d29df6)

**Comment by edterbak** [comment]
If you all are happy with the changes like described. let me know, I will close the issue (or you)

**Comment by MikeyMan83** [comment]
Looks very good! Cant wait to test :)

**Comment by BazemanKM** [comment]
Yes, this looks very good.
