### ISSUE TITLE
Softstart leads to a heavy on-off behaviour

### ISSUE THREAD

**Issue by mabek** [edterbak/NodeRed_Heishamon_control#99]
Hi,

for me enabling Softstart leads to a heavy on-off behaviour. See attached screenshot.
Before 7:30 heatpump was off and after 9:30 softstart was deactivated.
Not sure if a bug or wrong setting?
Version is 22.0.

![Softstart](https://user-images.githubusercontent.com/7482652/216006488-4e7e69f6-cf71-4a59-850b-c8bb7be7babb.png)

**Comment by edterbak** [comment]
Hi mabek,
Thank you for your reply. 
I am actually working on the softstart logic now. 

Can you tell me a little bit more?
what is the heishamon setting. 
> 1 How often new values are collected from heatpump:
> 2 How often all heatpump values are retransmitted to MQTT broker

My settings are 1: 10 seconds and 2: 60 seconds which seems to work nicely.

Any more info you can give me is welcome.

Just to confirm. Looking at the graph, the dark blue line, that looks to be the setpoint of the watertemperature. (correct?)
If so, it is at 22 degrees C? That would be too low for my pump. It will show that behaviour even without the function. 
The panasonic produces X amount of energy at the lowest possible compressor setting. @18-22Hz. 
If the amount X is not consumed by your house, the water temperature will rise above its setpoint, 22C
When the temp > 2C above the setpoint, it stops working. 
If the dark blue line is indeed the setpoint, 22C, than it seems the pump is in this last situation almost directly after start. 
The softstart function could also amplify this effect.

**Comment by mabek** [comment]
Hi, thanks a lot for your reply!
1: 25 seconds 2: 100 seconds.
I changed them to your suggested values with no impact on the behaviour.

However I think you are right about the Outlet setpoint which seems to be stuck at 22 degrees somehow. I have tried various settings that no impact on the Outlet setpoint:

 default water temperature, 
Heat water temperature limits
Temperature profile
Minimum temp.

I am using the built-in compensation curve and Heishamon shows me a different target temp:
TOP7 | Main_Target_Temp | 25 | °C

**Comment by edterbak** [comment]
On the settings tab, what are the Heat water temperature limits:
Minimum temp. xx
Maximum temp. xx
Maybe that is set incorrectly. should be 20 and high enough.

Ah, compensation curve built in the panasonic or the node red function?
I suspect the first. 

If so, can you check on the WAR tab, what the temperatures are after import.
You should be able to see the current calculated temparature of the water. 

To be honest, I have not built the node red flow to work perfectly **yet** with compensation curve from the internal panasonic. I will need to do some work to fix this. It is high on the agenda, but not within a couple of hours. More a week or two. 
In the meantime, I think it is better to set the heatpump in DIRECT mode.

**Comment by edterbak** [comment]
I have uploaded a major updated on the softstart function.
Can you give this a try if this solves your issues?

Also, the jumpy behaviour on/off, has it improved ? 
What pumpflow do you see when the compressor is active? is it high enough?
If your water is too slow, then it heats up to fast in the pump, causing the trip to stop again. (this is just a theory.)

**Comment by mabek** [comment]
Thanks a lot for the update! On/off behaviour seems to be fixed now.
Compressor frequency is also decreasing very quickly, starting from 33hz to 21-23hz in 2 minutes.

Just one quick question. Standard behaviour is that the frequency falls down to 19hz. Is that also possible with softstart?
